LIBM_CHEWOUT_FILES += \
	%D%/e_acosh.def \
	%D%/e_atanh.def \
	%D%/e_hypot.def \
	%D%/e_remainder.def \
	%D%/er_lgamma.def \
	%D%/s_acos.def \
	%D%/s_asine.def \
	%D%/s_asinh.def \
	%D%/s_atan.def \
	%D%/s_atan2.def \
	%D%/s_atangent.def \
	%D%/s_cosh.def \
	%D%/s_erf.def \
	%D%/s_exp.def \
	%D%/s_fabs.def \
	%D%/s_floor.def \
	%D%/s_fmod.def \
	%D%/s_frexp.def \
	%D%/s_ldexp.def \
	%D%/s_log10.def \
	%D%/s_logarithm.def \
	%D%/s_pow.def \
	%D%/s_sine.def \
	%D%/s_sineh.def \
	%D%/s_sqrt.def \
	%D%/s_tan.def \
	%D%/s_tanh.def \
	%D%/w_jn.def

LIBM_CHAPTERS += %D%/mathfp.tex
