#!/bin/sh    
set -e
HERE=`dirname "$0"`
"$HERE"/do-test coreboot-arm-eabi "$@"
"$HERE"/do-test coreboot-i386-elf "$@"
"$HERE"/do-test coreboot-riscv-elf "$@"
"$HERE"/do-test coreboot-x86_64-elf "$@"
