#!/bin/sh
set -e
HERE=`dirname "$0"`
"$HERE"/do-test-noopt riscv "$@"
"$HERE"/do-test-noopt clang-riscv "$@"
"$HERE"/do-test-noopt clang-rv32imafdc "$@"
"$HERE"/do-test-noopt rv32imac "$@"
"$HERE"/do-test or1k "$@"
