#!/bin/sh
TARGET=$1
DIR=build-"$TARGET"
CONFIGURE=do-"$TARGET"-configure
shift
git config --global --add safe.directory /picolibc
DOCKER_FILES="$DOCKERFILE $PACKAGES_FILE $EXTRA_FILE"

(mkdir "$DIR" || exit 1
 cd "$DIR" || exit 2
 date
 if [ -n "$BEFORE_SHA" -a -n "$AFTER_SHA" ]; then
     for f in $DOCKER_FILES; do
	 md5sum ../../$f > ../../$f.md5
     done
     echo '##################################################'
     echo '##########' git checkout $BEFORE_SHA
     echo '##################################################'
     git checkout $BEFORE_SHA
     case $? in
	 0)
	     echo 'Checkout before succeeded'
	     DOCKER_OK=y
	     for f in $DOCKER_FILES; do
		 if md5sum --check ../../$f.md5; then
		     echo "Docker file $f unchanged"
		 else
		     echo "Docker file $f changed"
		     DOCKER_OK=
		 fi
	     done
	     if [ -f ../scripts/check-ci -a -n "$DOCKER_OK" ]; then
		 echo 'docker files and check-ci script ok, doing incremental tests'
		 INC_TESTS=yes
	     else
		 echo 'docker files or check-ci script not ok'
		 echo '########' git checkout $AFTER_SHA
		 git checkout $AFTER_SHA
	     fi
	     ;;
	 *)
	     echo 'Checkout before failed'
	     git checkout $AFTER_SHA
	     ;;
     esac
 fi
 date
 echo '##########' ../scripts/"$CONFIGURE" -Dwerror=true -Ddebug=false "$@"
 ../scripts/"$CONFIGURE" -Dwerror=true -Ddebug=false "$@" > config.log 2>&1
 case $? in
     0)
	 echo 'Configuration succeeded'
	 ;;
     77)
	 echo 'Configuration skipped'
	 exit 0
	 ;;
     *)
	 exit 3
	 ;;
 esac
 TEST_WRAPPER=
 if grep -q 'Cross files' meson-logs/meson-setup.txt; then
     echo 'Cross build, no wrapper'
 else
     TEST_WRAPPER="--wrapper $PWD/../scripts/run-native"
 fi
 if [ -n "$INC_TESTS" ]; then
     date
     echo '########## incremental' "$TARGET" 'ninja'
     ninja > incremental.log 2>&1 || exit 4
     date
     INC_TEST_ARGS="$TEST_WRAPPER --no-suite headers --no-suite ctype-diff"
     echo '########## incremental' "$TARGET" "CI_CAPTURE=yes meson $INC_TEST_ARGS test"
     CI_CAPTURE=yes meson test $INC_TEST_ARGS > capture.log 2>&1 || exit 5
     echo '########## incremental' "$TARGET" "git checkout $AFTER_SHA"
     git checkout "$AFTER_SHA"
 fi
 date
 echo '##########' "$TARGET" ninja
 ninja > ninja.log 2>&1 || exit 6
 date
 echo '##########' "$TARGET" "meson test $TEST_WRAPPER -t 20"
 meson test $TEST_WRAPPER -t 20 > test.log 2>&1 || exit 7
 date
 grep -v ' SKIP ' test.log
 echo 'Test succeeded'
)
case $? in
    0)
	rm -rf "$DIR"
	;;
    1)
	echo '##################################'
	echo '############# mkdir' "$DIR" 'failed'
	echo '##################################'
	exit 1
	;;
    2)
	echo '##################################'
	echo '############# cd' "$DIR" 'failed'
	echo '##################################'
	exit 1
	;;
    3)
	echo '##################################'
	echo '############# Configuration failed'
	echo '##################################'
	echo 'config.log'
	echo '##################################'
	cat "$DIR"/config.log
	echo '##################################'
	echo 'meson-logs/meson-log.txt'
	echo '##################################'
	cat "$DIR"/meson-logs/meson-log.txt
	exit 1
	;;
    4)
	echo '##################################'
	echo '############# Incremental Build failed'
	echo '##################################'
	echo 'incremental.log'
	echo '##################################'
	cat "$DIR"/incremental.log
	exit 1
	;;
    5)
	echo '##################################'
	echo '############# Incremental Capture failed'
	echo '##################################'
	echo 'capture.log'
	echo '##################################'
	cat "$DIR"/capture.log
	echo '##################################'
	echo 'meson-logs/testlog.txt'
	echo '##################################'
	cat "$DIR"/meson-logs/testlog.txt
	exit 1
	;;
    6)
	echo '##################################'
	echo '############# Build failed'
	echo '##################################'
	echo 'ninja.log'
	echo '##################################'
	cat "$DIR"/ninja.log
	exit 1
	;;
    7)
	echo '##################################'
	echo '############# Test failed'
	echo '##################################'
	echo 'test.log'
	echo '##################################'
	cat "$DIR"/test.log
	echo '##################################'
	echo 'meson-logs/testlog.txt'
	echo '##################################'
	cat "$DIR"/meson-logs/testlog.txt
	exit 1
	;;
    *)
	echo '##################################'
	echo '############# Unknown failure' "$?"
	echo '##################################'
	cat "$DIR"/meson-logs/*
	exit 1
	;;
esac
