#!/bin/sh
set -e
HERE=`dirname "$0"`
"$HERE"/do-zephyr-test aarch64-zephyr "$@"
"$HERE"/do-zephyr-test arc "$@"
"$HERE"/do-zephyr-test arc64 "$@"
"$HERE"/do-zephyr-test arm-zephyr "$@"
"$HERE"/do-zephyr-test clang-aarch64 "$@"
#"$HERE"/do-zephyr-test clang-arm "$@" # blocked by bug in compiler-rt
"$HERE"/do-zephyr-test clang-riscv "$@"
"$HERE"/do-zephyr-build microblazeel "$@"
"$HERE"/do-zephyr-test mips-zephyr "$@"
"$HERE"/do-zephyr-test riscv-zephyr "$@"
"$HERE"/do-zephyr-test rx-zephyr-elf "$@"
"$HERE"/do-zephyr-test sparc-zephyr "$@"
"$HERE"/do-zephyr-test x86_64-zephyr "$@"
"$HERE"/do-zephyr-test xtensa-dc233c "$@"
"$HERE"/do-zephyr-build xtensa-espressif_esp32 "$@"
"$HERE"/do-zephyr-build xtensa-espressif_esp32s2 "$@"
"$HERE"/do-zephyr-build xtensa-nxp_imx_adsp "$@"
"$HERE"/do-zephyr-build xtensa-nxp_imx8m_adsp "$@"
"$HERE"/do-zephyr-build xtensa-sample_controller "$@"
