#!/bin/sh
set -e
HERE=`dirname "$0"`
"$HERE"/do-zephyr-test arc "$@"
"$HERE"/do-zephyr-build arc64 "$@"
"$HERE"/do-zephyr-build microblazeel "$@"
"$HERE"/do-zephyr-build nios2 "$@"
"$HERE"/do-zephyr-test x86_64-zephyr "$@"
"$HERE"/do-zephyr-build xtensa-espressif_esp32 "$@"
"$HERE"/do-zephyr-build xtensa-espressif_esp32s2 "$@"
"$HERE"/do-zephyr-build xtensa-nxp_imx_adsp "$@"
"$HERE"/do-zephyr-build xtensa-nxp_imx8m_adsp "$@"
"$HERE"/do-zephyr-build xtensa-sample_controller "$@"
