FROM debian:testing

COPY .github/packages.txt /

COPY .github/zephyr-files.txt /

RUN apt-get update && \
    apt-get install -y wget gnupg && \
    (apt-get update || apt-get update || apt-get update) && \
    (apt-get upgrade -y || apt-get upgrade -y || apt-get upgrade -y) && \
    (xargs -a packages.txt apt-get install -y --no-install-recommends || \
     xargs -a packages.txt apt-get install -y --no-install-recommends || \
     xargs -a packages.txt apt-get install -y --no-install-recommends || \
     xargs -a packages.txt apt-get install -y --no-install-recommends) && \
    mkdir -p /opt && \
    (cd /opt && while read file; do wget $file || exit 1; tar xf `basename $file`; done) < zephyr-files.txt

RUN apt-get clean
