#!/bin/bash
here=`dirname "$0"`
for sdk in /opt/zephyr-sdk-0.17.4 /opt /fail; do
    if [ -d $sdk/aarch64-zephyr-elf ]; then
	break
    fi
done

case $sdk in
    /fail)
	echo 'No Zephyr SDK found' 1>&2
	exit 1
	;;
esac
	
export ZEPHYR_SDK_INSTALL_DIR=$sdk

for hosttools in . zephyr-sdk-hosttools fail; do
    if [ -f $sdk/$hosttools/environment-setup-* ]; then
	break
    fi
done

case $hosttools in
    fail)
	echo 'No Zephyr host tools found' 1>&2
	exit 1
	;;
esac

. $ZEPHYR_SDK_INSTALL_DIR/$hosttools/environment-setup-*

for dir in "$ZEPHYR_SDK_INSTALL_DIR"/* "$ZEPHYR_SDK_INSTALL_DIR"/qemu*; do
    if [ -d "$dir" -a -d "$dir"/bin ]; then
	PATH="$dir"/bin:$PATH
    fi
done

exec "$@"
