#!/bin/sh
ARCH=arm-none-eabi
DIR=`dirname $0`
meson "$DIR" \
	-Dincludedir=picolibc/$ARCH/include \
	-Dlibdir=picolibc/$ARCH/lib \
	-Dprefix="$(readlink -f $(${ARCH}-gcc -print-sysroot))" \
	-Dsysroot-install=true \
	--cross-file "$DIR"/cross-$ARCH.txt \
	"$@"
