#!/bin/sh
DIR=`dirname $0`
meson $DIR \
        -Dtls-model=global-dynamic \
        -Dmultilib=false \
        -Dpicolib=false \
	-Dnewlib-global-atexit=true\
	-Dincludedir=lib/picolibc/include \
	-Dlibdir=lib/picolibc/lib \
	-Dtests=true \
	"$@"
