#!/bin/sh
DIR=`dirname $0`
meson $DIR \
        -Dtarget-optspace=true \
        -Dpicolib=false \
	-Dnewlib-tinystdio=true \
	-Dnewlib-supplied-syscalls=false \
	-Dnewlib-reentrant-small=true\
	-Dnewlib-wide-orient=false\
	-Dnewlib-nano-malloc=true\
	-Dnewlib-reent-small=true\
	-Dlite-exit=true\
	-Dnewlib-mb=false\
	-Dnewlib-global-atexit=true\
	-Dnewlib-global-errno=true\
	-Dincludedir=lib/newlib-nano/include \
	-Dlibdir=lib/newlib-nano/lib \
	-Dtests=true \
	--buildtype debug
