#!/bin/sh
DIR=`dirname $0`
ARCH=i386-linux-gnu
meson "$DIR" \
        -Dtls-model=global-dynamic \
        -Dmultilib=false \
	-Dincludedir=picolibc/$ARCH/include \
	-Dlibdir=picolibc/$ARCH/lib \
	--cross-file "$DIR"/cross-$ARCH.txt \
	-Dtests=true \
	"$@"
