//;# autogenerated:  Do not edit.

//; $tls::start_offset = -12800;
//; $tls::locals = -12800;
//; $tls::plocals = 0;
//; $tls::local_clib = -10624;
//; $tls::plocal_clib = 2176;
//; $tls::__dontuse = -10624;
//; $tls::p__dontuse = 2176;
//; $tls::func = -8736;
//; $tls::pfunc = 4064;
//; $tls::saved_errno = -8728;
//; $tls::psaved_errno = 4072;
//; $tls::sa_flags = -8724;
//; $tls::psa_flags = 4076;
//; $tls::oldmask = -8720;
//; $tls::poldmask = 4080;
//; $tls::deltamask = -8712;
//; $tls::pdeltamask = 4088;
//; $tls::errno_addr = -8704;
//; $tls::perrno_addr = 4096;
//; $tls::sigmask = -8696;
//; $tls::psigmask = 4104;
//; $tls::sigwait_mask = -8688;
//; $tls::psigwait_mask = 4112;
//; $tls::altstack = -8680;
//; $tls::paltstack = 4120;
//; $tls::sigwait_info = -8656;
//; $tls::psigwait_info = 4144;
//; $tls::signal_arrived = -8648;
//; $tls::psignal_arrived = 4152;
//; $tls::will_wait_for_signal = -8640;
//; $tls::pwill_wait_for_signal = 4160;
//; $tls::thread_context = -8632;
//; $tls::pthread_context = 4168;
//; $tls::thread_id = -7400;
//; $tls::pthread_id = 5400;
//; $tls::infodata = -7396;
//; $tls::pinfodata = 5404;
//; $tls::tid = -7248;
//; $tls::ptid = 5552;
//; $tls::_ctinfo = -7240;
//; $tls::p_ctinfo = 5560;
//; $tls::andreas = -7232;
//; $tls::pandreas = 5568;
//; $tls::wq = -7224;
//; $tls::pwq = 5576;
//; $tls::sig = -7176;
//; $tls::psig = 5624;
//; $tls::incyg = -7172;
//; $tls::pincyg = 5628;
//; $tls::spinning = -7168;
//; $tls::pspinning = 5632;
//; $tls::stacklock = -7164;
//; $tls::pstacklock = 5636;
//; $tls::stackptr = -7160;
//; $tls::pstackptr = 5640;
//; $tls::stack = -7152;
//; $tls::pstack = 5648;
//; $tls::initialized = -5104;
//; $tls::pinitialized = 7696;
//; __DATA__

#define tls_locals (-12800)
#define tls_plocals (0)
#define tls_local_clib (-10624)
#define tls_plocal_clib (2176)
#define tls___dontuse (-10624)
#define tls_p__dontuse (2176)
#define tls_func (-8736)
#define tls_pfunc (4064)
#define tls_saved_errno (-8728)
#define tls_psaved_errno (4072)
#define tls_sa_flags (-8724)
#define tls_psa_flags (4076)
#define tls_oldmask (-8720)
#define tls_poldmask (4080)
#define tls_deltamask (-8712)
#define tls_pdeltamask (4088)
#define tls_errno_addr (-8704)
#define tls_perrno_addr (4096)
#define tls_sigmask (-8696)
#define tls_psigmask (4104)
#define tls_sigwait_mask (-8688)
#define tls_psigwait_mask (4112)
#define tls_altstack (-8680)
#define tls_paltstack (4120)
#define tls_sigwait_info (-8656)
#define tls_psigwait_info (4144)
#define tls_signal_arrived (-8648)
#define tls_psignal_arrived (4152)
#define tls_will_wait_for_signal (-8640)
#define tls_pwill_wait_for_signal (4160)
#define tls_thread_context (-8632)
#define tls_pthread_context (4168)
#define tls_thread_id (-7400)
#define tls_pthread_id (5400)
#define tls_infodata (-7396)
#define tls_pinfodata (5404)
#define tls_tid (-7248)
#define tls_ptid (5552)
#define tls__ctinfo (-7240)
#define tls_p_ctinfo (5560)
#define tls_andreas (-7232)
#define tls_pandreas (5568)
#define tls_wq (-7224)
#define tls_pwq (5576)
#define tls_sig (-7176)
#define tls_psig (5624)
#define tls_incyg (-7172)
#define tls_pincyg (5628)
#define tls_spinning (-7168)
#define tls_pspinning (5632)
#define tls_stacklock (-7164)
#define tls_pstacklock (5636)
#define tls_stackptr (-7160)
#define tls_pstackptr (5640)
#define tls_stack (-7152)
#define tls_pstack (5648)
#define tls_initialized (-5104)
#define tls_pinitialized (7696)
