//;# autogenerated:  Do not edit.

//; $tls::sizeof__cygtls = 3972;
//; $tls::func = -3972;
//; $tls::pfunc = 0;
//; $tls::saved_errno = -3968;
//; $tls::psaved_errno = 4;
//; $tls::sa_flags = -3964;
//; $tls::psa_flags = 8;
//; $tls::oldmask = -3960;
//; $tls::poldmask = 12;
//; $tls::deltamask = -3956;
//; $tls::pdeltamask = 16;
//; $tls::event = -3952;
//; $tls::pevent = 20;
//; $tls::errno_addr = -3948;
//; $tls::perrno_addr = 24;
//; $tls::initialized = -3944;
//; $tls::pinitialized = 28;
//; $tls::sigmask = -3940;
//; $tls::psigmask = 32;
//; $tls::sigwait_mask = -3936;
//; $tls::psigwait_mask = 36;
//; $tls::sigwait_info = -3932;
//; $tls::psigwait_info = 40;
//; $tls::threadkill = -3928;
//; $tls::pthreadkill = 44;
//; $tls::infodata = -3924;
//; $tls::pinfodata = 48;
//; $tls::tid = -3776;
//; $tls::ptid = 196;
//; $tls::local_clib = -3772;
//; $tls::plocal_clib = 200;
//; $tls::__dontuse = -3772;
//; $tls::p__dontuse = 200;
//; $tls::locals = -2708;
//; $tls::plocals = 1264;
//; $tls::_ctinfo = -1084;
//; $tls::p_ctinfo = 2888;
//; $tls::wq = -1080;
//; $tls::pwq = 2892;
//; $tls::prev = -1052;
//; $tls::pprev = 2920;
//; $tls::next = -1048;
//; $tls::pnext = 2924;
//; $tls::stackptr = -1044;
//; $tls::pstackptr = 2928;
//; $tls::sig = -1040;
//; $tls::psig = 2932;
//; $tls::incyg = -1036;
//; $tls::pincyg = 2936;
//; $tls::spinning = -1032;
//; $tls::pspinning = 2940;
//; $tls::stacklock = -1028;
//; $tls::pstacklock = 2944;
//; $tls::stack = -1024;
//; $tls::pstack = 2948;
//; $tls::padding = 0;
//; $tls::ppadding = 3972;
//; __DATA__

#define tls_func (-3972)
#define tls_pfunc (0)
#define tls_saved_errno (-3968)
#define tls_psaved_errno (4)
#define tls_sa_flags (-3964)
#define tls_psa_flags (8)
#define tls_oldmask (-3960)
#define tls_poldmask (12)
#define tls_deltamask (-3956)
#define tls_pdeltamask (16)
#define tls_event (-3952)
#define tls_pevent (20)
#define tls_errno_addr (-3948)
#define tls_perrno_addr (24)
#define tls_initialized (-3944)
#define tls_pinitialized (28)
#define tls_sigmask (-3940)
#define tls_psigmask (32)
#define tls_sigwait_mask (-3936)
#define tls_psigwait_mask (36)
#define tls_sigwait_info (-3932)
#define tls_psigwait_info (40)
#define tls_threadkill (-3928)
#define tls_pthreadkill (44)
#define tls_infodata (-3924)
#define tls_pinfodata (48)
#define tls_tid (-3776)
#define tls_ptid (196)
#define tls_local_clib (-3772)
#define tls_plocal_clib (200)
#define tls___dontuse (-3772)
#define tls_p__dontuse (200)
#define tls_locals (-2708)
#define tls_plocals (1264)
#define tls__ctinfo (-1084)
#define tls_p_ctinfo (2888)
#define tls_wq (-1080)
#define tls_pwq (2892)
#define tls_prev (-1052)
#define tls_pprev (2920)
#define tls_next (-1048)
#define tls_pnext (2924)
#define tls_stackptr (-1044)
#define tls_pstackptr (2928)
#define tls_sig (-1040)
#define tls_psig (2932)
#define tls_incyg (-1036)
#define tls_pincyg (2936)
#define tls_spinning (-1032)
#define tls_pspinning (2940)
#define tls_stacklock (-1028)
#define tls_pstacklock (2944)
#define tls_stack (-1024)
#define tls_pstack (2948)
#define tls_padding (0)
#define tls_ppadding (3972)
