//;# autogenerated:  Do not edit.

//; $tls::start_offset = -12700;
//; $tls::locals = -12700;
//; $tls::plocals = 0;
//; $tls::local_clib = -11300;
//; $tls::plocal_clib = 1400;
//; $tls::__dontuse = -11300;
//; $tls::p__dontuse = 1400;
//; $tls::func = -10212;
//; $tls::pfunc = 2488;
//; $tls::saved_errno = -10208;
//; $tls::psaved_errno = 2492;
//; $tls::sa_flags = -10204;
//; $tls::psa_flags = 2496;
//; $tls::oldmask = -10200;
//; $tls::poldmask = 2500;
//; $tls::deltamask = -10196;
//; $tls::pdeltamask = 2504;
//; $tls::errno_addr = -10192;
//; $tls::perrno_addr = 2508;
//; $tls::sigmask = -10188;
//; $tls::psigmask = 2512;
//; $tls::sigwait_mask = -10184;
//; $tls::psigwait_mask = 2516;
//; $tls::sigwait_info = -10180;
//; $tls::psigwait_info = 2520;
//; $tls::signal_arrived = -10176;
//; $tls::psignal_arrived = 2524;
//; $tls::will_wait_for_signal = -10172;
//; $tls::pwill_wait_for_signal = 2528;
//; $tls::thread_context = -10168;
//; $tls::pthread_context = 2532;
//; $tls::thread_id = -9956;
//; $tls::pthread_id = 2744;
//; $tls::infodata = -9952;
//; $tls::pinfodata = 2748;
//; $tls::tid = -9804;
//; $tls::ptid = 2896;
//; $tls::_ctinfo = -9800;
//; $tls::p_ctinfo = 2900;
//; $tls::andreas = -9796;
//; $tls::pandreas = 2904;
//; $tls::wq = -9792;
//; $tls::pwq = 2908;
//; $tls::sig = -9764;
//; $tls::psig = 2936;
//; $tls::incyg = -9760;
//; $tls::pincyg = 2940;
//; $tls::spinning = -9756;
//; $tls::pspinning = 2944;
//; $tls::stacklock = -9752;
//; $tls::pstacklock = 2948;
//; $tls::stackptr = -9748;
//; $tls::pstackptr = 2952;
//; $tls::stack = -9744;
//; $tls::pstack = 2956;
//; $tls::initialized = -8720;
//; $tls::pinitialized = 3980;
//; __DATA__

#define tls_locals (-12700)
#define tls_plocals (0)
#define tls_local_clib (-11300)
#define tls_plocal_clib (1400)
#define tls___dontuse (-11300)
#define tls_p__dontuse (1400)
#define tls_func (-10212)
#define tls_pfunc (2488)
#define tls_saved_errno (-10208)
#define tls_psaved_errno (2492)
#define tls_sa_flags (-10204)
#define tls_psa_flags (2496)
#define tls_oldmask (-10200)
#define tls_poldmask (2500)
#define tls_deltamask (-10196)
#define tls_pdeltamask (2504)
#define tls_errno_addr (-10192)
#define tls_perrno_addr (2508)
#define tls_sigmask (-10188)
#define tls_psigmask (2512)
#define tls_sigwait_mask (-10184)
#define tls_psigwait_mask (2516)
#define tls_sigwait_info (-10180)
#define tls_psigwait_info (2520)
#define tls_signal_arrived (-10176)
#define tls_psignal_arrived (2524)
#define tls_will_wait_for_signal (-10172)
#define tls_pwill_wait_for_signal (2528)
#define tls_thread_context (-10168)
#define tls_pthread_context (2532)
#define tls_thread_id (-9956)
#define tls_pthread_id (2744)
#define tls_infodata (-9952)
#define tls_pinfodata (2748)
#define tls_tid (-9804)
#define tls_ptid (2896)
#define tls__ctinfo (-9800)
#define tls_p_ctinfo (2900)
#define tls_andreas (-9796)
#define tls_pandreas (2904)
#define tls_wq (-9792)
#define tls_pwq (2908)
#define tls_sig (-9764)
#define tls_psig (2936)
#define tls_incyg (-9760)
#define tls_pincyg (2940)
#define tls_spinning (-9756)
#define tls_pspinning (2944)
#define tls_stacklock (-9752)
#define tls_pstacklock (2948)
#define tls_stackptr (-9748)
#define tls_pstackptr (2952)
#define tls_stack (-9744)
#define tls_pstack (2956)
#define tls_initialized (-8720)
#define tls_pinitialized (3980)
