#ifndef _REGSTR_H
#define _REGSTR_H
#ifdef __cplusplus
extern "C" {
#endif
#define REGSTR_KEY_CLASS _TEXT("Class")
#define REGSTR_KEY_CONFIG _TEXT("Config")
#define REGSTR_KEY_ENUM _TEXT("Enum")
#define REGSTR_KEY_ROOTENUM _TEXT("Root")
#define REGSTR_KEY_BIOSENUM _TEXT("BIOS")
#define REGSTR_KEY_PCMCIAENUM _TEXT("PCMCIA")
#define REGSTR_KEY_PCIENUM _TEXT("PCI")
#define REGSTR_KEY_LOGCONFIG	_TEXT("LogConfig")
#define REGSTR_KEY_SYSTEMBOARD	_TEXT("*PNP0C01")
#define REGSTR_KEY_APM	_TEXT("*PNP0C05")
#define REGSTR_KEY_INIUPDATE	_TEXT("IniUpdate")
#define REG_KEY_INSTDEV _TEXT("Installed")
#define REGSTR_KEY_DOSOPTCDROM	_TEXT("CD-ROM")
#define REGSTR_KEY_DOSOPTMOUSE	_TEXT("MOUSE")
#define REGSTR_DEFAULT_INSTANCE _TEXT("0000")
#define REGSTR_PATH_MOTHERBOARD REGSTR_KEY_SYSTEMBOARD _TEXT("\\" REGSTR_DEFAULT_INSTANCE
#define REGSTR_PATH_SETUP	_TEXT("Software\\Microsoft\\Windows\\CurrentVersion")
#define REGSTR_PATH_PIFCONVERT _TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\PIFConvert")
#define REGSTR_PATH_MSDOSOPTS	_TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\MS-DOSOptions")
#define REGSTR_PATH_MSDOSEMU	_TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\MS-DOS Emulation")
#define REGSTR_PATH_NEWDOSBOX	_TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\MS-DOS Emulation\\AppCompat")
#define REGSTR_PATH_RUNONCE	_TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\RunOnce")
#define REGSTR_PATH_RUN	_TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\Run")
#define REGSTR_PATH_RUNSERVICESONCE	_TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\RunServicesOnce")
#define REGSTR_PATH_RUNSERVICES	_TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\RunServices")
#define REGSTR_PATH_EXPLORER	_TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\Explorer")
#define REGSTR_PATH_DETECT	_TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\Detect")
#define REGSTR_PATH_APPPATHS	_TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\App Paths")
#define REGSTR_PATH_UNINSTALL _TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall")
#define REGSTR_PATH_REALMODENET _TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\Network\\Real Mode Net")
#define REGSTR_PATH_NETEQUIV _TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\Network\\Equivalent")
#define REGSTR_PATH_CVNETWORK _TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\Network")
#define REGSTR_PATH_IDCONFIGDB	_TEXT("System\\CurrentControlSet\\Control\\IDConfigDB")
#define REGSTR_PATH_CLASS	_TEXT("System\\CurrentControlSet\\Services\\Class")
#define REGSTR_PATH_DISPLAYSETTINGS _TEXT("Display\\Settings")
#define REGSTR_PATH_FONTS	_TEXT("Display\\Fonts")
#define REGSTR_PATH_ENUM	_TEXT("Enum")
#define REGSTR_PATH_ROOT	_TEXT("Enum\\Root")
#define REGSTR_PATH_SERVICES	_TEXT("System\\CurrentControlSet\\Services")
#define REGSTR_PATH_VXD _TEXT("System\\CurrentControlSet\\Services\\VxD")
#define REGSTR_PATH_IOS _TEXT("System\\CurrentControlSet\\Services\\VxD\\IOS")
#define REGSTR_PATH_VMM _TEXT("System\\CurrentControlSet\\Services\\VxD\\VMM")
#define REGSTR_PATH_VPOWERD _TEXT("System\\CurrentControlSet\\Services\\VxD\\VPOWERD")
#define REGSTR_PATH_VNETSUP _TEXT("System\\CurrentControlSet\\Services\\VxD\\VNETSUP")
#define REGSTR_PATH_NWREDIR _TEXT("System\\CurrentControlSet\\Services\\VxD\\NWREDIR")
#define REGSTR_PATH_NCPSERVER _TEXT("System\\CurrentControlSet\\Services\\NcpServer\\Parameters")
#define REGSTR_PATH_IOARB	_TEXT("System\\CurrentControlSet\\Services\\Arbitrators\\IOArb")
#define REGSTR_PATH_ADDRARB	_TEXT("System\\CurrentControlSet\\Services\\Arbitrators\\AddrArb")
#define REGSTR_PATH_DMAARB	_TEXT("System\\CurrentControlSet\\Services\\Arbitrators\\DMAArb")
#define REGSTR_PATH_IRQARB	_TEXT("System\\CurrentControlSet\\Services\\Arbitrators\\IRQArb")
#define REGSTR_PATH_CODEPAGE	_TEXT("System\\CurrentControlSet\\Control\\Nls\\Codepage")
#define REGSTR_PATH_FILESYSTEM	_TEXT("System\\CurrentControlSet\\Control\\FileSystem")
#define REGSTR_PATH_FILESYSTEM_NOVOLTRACK	_TEXT("System\\CurrentControlSet\\Control\\FileSystem\\NoVolTrack")
#define REGSTR_PATH_CDFS	_TEXT("System\\CurrentControlSet\\Control\\FileSystem\\CDFS")
#define REGSTR_PATH_WINBOOT	_TEXT("System\\CurrentControlSet\\Control\\WinBoot")
#define REGSTR_PATH_INSTALLEDFILES	_TEXT("System\\CurrentControlSet\\Control\\InstalledFiles")
#define REGSTR_PATH_VMM32FILES	_TEXT("System\\CurrentControlSet\\Control\\VMM32Files")
#define REGSTR_MAX_VALUE_LENGTH 256
#define REGSTR_VAL_BITSPERPIXEL	_TEXT("BitsPerPixel")
#define REGSTR_VAL_RESOLUTION _TEXT("Resolution")
#define REGSTR_VAL_DPILOGICALX	_TEXT("DPILogicalX")
#define REGSTR_VAL_DPILOGICALY	_TEXT("DPILogicalY")
#define REGSTR_VAL_DPIPHYSICALX	_TEXT("DPIPhysicalX")
#define REGSTR_VAL_DPIPHYSICALY _TEXT("DPIPhysicalY")
#define REGSTR_VAL_REFRESHRATE _TEXT("RefreshRate")
#define REGSTR_VAL_DISPLAYFLAGS _TEXT("DisplayFlags")
#define REGSTR_PATH_CONTROLPANEL _TEXT("Control Panel")
#define REGSTR_PATH_CONTROLSFOLDER _TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\Controls Folder")
#define REGSTR_VAL_DOSCP	_TEXT("OEMCP")
#define REGSTR_VAL_WINCP	_TEXT("ACP")
#define REGSTR_PATH_DYNA_ENUM	_TEXT("Config Manager\\Enum")
#define	REGSTR_VAL_HARDWARE_KEY	_TEXT("HardWareKey")
#define	REGSTR_VAL_ALLOCATION	_TEXT("Allocation")
#define	REGSTR_VAL_PROBLEM	_TEXT("Problem")
#define	REGSTR_VAL_STATUS	_TEXT("Status")
#define REGSTR_VAL_DONTUSEMEM	_TEXT("DontAllocLastMem")
#define REGSTR_VAL_SYSTEMROOT _TEXT("SystemRoot")
#define REGSTR_VAL_BOOTCOUNT	_TEXT("BootCount")
#define REGSTR_VAL_REALNETSTART	_TEXT("RealNetStart")
#define	REGSTR_VAL_MEDIA	_TEXT("MediaPath")
#define	REGSTR_VAL_CONFIG	_TEXT("ConfigPath")
#define REGSTR_VAL_DEVICEPATH	_TEXT("DevicePath")
#define REGSTR_VAL_SRCPATH	_TEXT("SourcePath")
#define REGSTR_VAL_OLDWINDIR	_TEXT("OldWinDir")
#define REGSTR_VAL_SETUPFLAGS	_TEXT("SetupFlags")
#define REGSTR_VAL_REGOWNER _TEXT("RegisteredOwner")
#define REGSTR_VAL_REGORGANIZATION _TEXT("RegisteredOrganization")
#define REGSTR_VAL_LICENSINGINFO _TEXT("LicensingInfo")
#define REGSTR_VAL_OLDMSDOSVER _TEXT("OldMSDOSVer")
#define REGSTR_VAL_FIRSTINSTALLDATETIME _TEXT("FirstInstallDateTime")
#define REGSTR_VAL_INSTALLTYPE	_TEXT("InstallType")
#define REGSTR_VAL_WRAPPER	_TEXT("Wrapper")
#define IT_COMPACT 0
#define IT_TYPICAL 1
#define IT_PORTABLE 2
#define IT_CUSTOM 3
#define REGSTR_KEY_SETUP	_TEXT("\\Setup")
#define REGSTR_VAL_BOOTDIR _TEXT("BootDir")
#define REGSTR_VAL_WINBOOTDIR _TEXT("WinbootDir")
#define REGSTR_VAL_WINDIR	_TEXT("WinDir")
#define REGSTR_VAL_APPINSTPATH	_TEXT("AppInstallPath")
#define REGSTR_PATH_EBD REGSTR_PATH_SETUP REGSTR_KEY_SETUP _TEXT("\\EBD")
#define REGSTR_KEY_EBDFILESLOCAL _TEXT("EBDFilesLocale")
#define REGSTR_KEY_EBDFILESKEYBOARD _TEXT("EBDFilesKeyboard")
#define REGSTR_KEY_EBDAUTOEXECBATLOCAL _TEXT("EBDAutoexecBatLocale")
#define REGSTR_KEY_EBDAUTOEXECBATKEYBOARD _TEXT("EBDAutoexecBatKeyboard")
#define REGSTR_KEY_EBDCONFIGSYSLOCAL _TEXT("EBDConfigSysLocale")
#define REGSTR_KEY_EBDCONFIGSYSKEYBOARD _TEXT("EBDConfigSysKeyboard")
#define REGSTR_VAL_MSDOSMODE _TEXT("MSDOSMode")
#define REGSTR_VAL_MSDOSMODEDISCARD _TEXT("Discard")
#define REGSTR_VAL_DOSOPTGLOBALFLAGS	_TEXT("GlobalFlags")
#define DOSOPTGF_DEFCLEAN 1
#define REGSTR_VAL_DOSOPTFLAGS	_TEXT("Flags")
#define REGSTR_VAL_OPTORDER	_TEXT("Order")
#define REGSTR_VAL_CONFIGSYS	_TEXT("Config.Sys")
#define REGSTR_VAL_AUTOEXEC	_TEXT("Autoexec.Bat")
#define REGSTR_VAL_STDDOSOPTION _TEXT("StdOption")
#define REGSTR_VAL_DOSOPTTIP	_TEXT("TipText")
#define DOSOPTF_DEFAULT 1
#define DOSOPTF_SUPPORTED 2
#define DOSOPTF_ALWAYSUSE 4
#define DOSOPTF_USESPMODE 8
#define DOSOPTF_PROVIDESUMB 16
#define DOSOPTF_NEEDSETUP 32
#define DOSOPTF_INDOSSTART 64
#define DOSOPTF_MULTIPLE 128
#define SUF_FIRSTTIME 1
#define SUF_EXPRESS 2
#define SUF_BATCHINF 4
#define SUF_CLEAN 8
#define SUF_INSETUP 16
#define SUF_NETSETUP 32
#define SUF_NETHDBOOT 64
#define SUF_NETRPLBOOT 128
#define SUF_SBSCOPYOK 256
#define REGSTR_VAL_DOSPAGER	_TEXT("DOSPager")
#define REGSTR_VAL_VXDGROUPS	_TEXT("VXDGroups")
#define REGSTR_VAL_VPOWERDFLAGS _TEXT("Flags")
#define VPDF_DISABLEPWRMGMT 1
#define VPDF_FORCEAPM10MODE 2
#define VPDF_SKIPINTELSLCHECK 4
#define VPDF_DISABLEPWRSTATUSPOLL 8
#define REGSTR_VAL_WORKGROUP _TEXT("Workgroup")
#define REGSTR_VAL_DIRECTHOST _TEXT("DirectHost")
#define REGSTR_VAL_FILESHARING _TEXT("FileSharing")
#define REGSTR_VAL_PRINTSHARING	_TEXT("PrintSharing")
#define REGSTR_VAL_FIRSTNETDRIVE _TEXT("FirstNetworkDrive")
#define REGSTR_VAL_MAXCONNECTIONS	_TEXT("MaxConnections")
#define REGSTR_VAL_APISUPPORT	_TEXT("APISupport")
#define REGSTR_VAL_MAXRETRY	_TEXT("MaxRetry")
#define REGSTR_VAL_MINRETRY	_TEXT("MinRetry")
#define REGSTR_VAL_SUPPORTLFN	_TEXT("SupportLFN")
#define REGSTR_VAL_SUPPORTBURST	_TEXT("SupportBurst")
#define REGSTR_VAL_SUPPORTTUNNELLING	_TEXT("SupportTunnelling")
#define REGSTR_VAL_FULLTRACE	_TEXT("FullTrace")
#define REGSTR_VAL_READCACHING	_TEXT("ReadCaching")
#define REGSTR_VAL_SHOWDOTS	_TEXT("ShowDots")
#define REGSTR_VAL_GAPTIME	_TEXT("GapTime")
#define REGSTR_VAL_SEARCHMODE	_TEXT("SearchMode")
#define REGSTR_VAL_SHELLVERSION _TEXT("ShellVersion")
#define REGSTR_VAL_MAXLIP _TEXT("MaxLIP")
#define REGSTR_VAL_PRESERVECASE _TEXT("PreserveCase")
#define REGSTR_VAL_OPTIMIZESFN _TEXT("OptimizeSFN")
#define REGSTR_VAL_NCP_BROWSEMASTER _TEXT("BrowseMaster")
#define	REGSTR_VAL_NCP_USEPEERBROWSING	_TEXT("Use_PeerBrowsing")
#define REGSTR_VAL_NCP_USESAP _TEXT("Use_Sap")
#define	REGSTR_VAL_WIN31FILESYSTEM	_TEXT("Win31FileSystem")
#define REGSTR_VAL_PRESERVELONGNAMES	_TEXT("PreserveLongNames")
#define REGSTR_VAL_DRIVEWRITEBEHIND	_TEXT("DriveWriteBehind")
#define REGSTR_VAL_ASYNCFILECOMMIT	_TEXT("AsyncFileCommit")
#define REGSTR_VAL_PATHCACHECOUNT	_TEXT("PathCache")
#define REGSTR_VAL_NAMECACHECOUNT	_TEXT("NameCache")
#define REGSTR_VAL_CONTIGFILEALLOC	_TEXT("ContigFileAllocSize")
#define REGSTR_VAL_VOLIDLETIMEOUT	_TEXT("VolumeIdleTimeout")
#define REGSTR_VAL_BUFFIDLETIMEOUT	_TEXT("BufferIdleTimeout")
#define REGSTR_VAL_BUFFAGETIMEOUT	_TEXT("BufferAgeTimeout")
#define	REGSTR_VAL_NAMENUMERICTAIL _TEXT("NameNumericTail")
#define	REGSTR_VAL_READAHEADTHRESHOLD	_TEXT("ReadAheadThreshold")
#define	REGSTR_VAL_DOUBLEBUFFER _TEXT("DoubleBuffer")
#define	REGSTR_VAL_SOFTCOMPATMODE _TEXT("SoftCompatMode")
#define REGSTR_VAL_DRIVESPINDOWN	_TEXT("DriveSpinDown")
#define	REGSTR_VAL_FORCEPMIO	_TEXT("ForcePMIO")
#define REGSTR_VAL_FORCERMIO	_TEXT("ForceRMIO")
#define REGSTR_VAL_LASTBOOTPMDRVS	_TEXT("LastBootPMDrvs")
#define REGSTR_VAL_VIRTUALHDIRQ	_TEXT("VirtualHDIRQ")
#define REGSTR_VAL_SRVNAMECACHECOUNT	_TEXT("ServerNameCacheMax")
#define REGSTR_VAL_SRVNAMECACHE	_TEXT("ServerNameCache")
#define REGSTR_VAL_SRVNAMECACHENETPROV	_TEXT("ServerNameCacheNumNets")
#define	REGSTR_VAL_AUTOMOUNT	_TEXT("AutoMountDrives")
#define	REGSTR_VAL_COMPRESSIONMETHOD	_TEXT("CompressionAlgorithm")
#define	REGSTR_VAL_COMPRESSIONTHRESHOLD	_TEXT("CompressionThreshold")
#define REGSTR_VAL_CDCACHESIZE	_TEXT("CacheSize")
#define REGSTR_VAL_CDPREFETCH	_TEXT("Prefetch")
#define REGSTR_VAL_CDPREFETCHTAIL _TEXT("PrefetchTail")
#define REGSTR_VAL_CDRAWCACHE	_TEXT("RawCache")
#define REGSTR_VAL_CDEXTERRORS	_TEXT("ExtendedErrors")
#define REGSTR_VAL_CDSVDSENSE	_TEXT("SVDSense")
#define REGSTR_VAL_CDSHOWVERSIONS _TEXT("ShowVersions")
#define REGSTR_VAL_CDCOMPATNAMES _TEXT("MSCDEXCompatNames")
#define REGSTR_VAL_CDNOREADAHEAD _TEXT("NoReadAhead")
#define REGSTR_VAL_SCSI	_TEXT("SCSI\\")
#define REGSTR_VAL_ESDI	_TEXT("ESDI\\")
#define REGSTR_VAL_FLOP _TEXT("FLOP\\")
#define	REGSTR_VAL_DISK	_TEXT("GenDisk")
#define	REGSTR_VAL_CDROM	_TEXT("GenCD")
#define	REGSTR_VAL_TAPE	_TEXT("TAPE")
#define	REGSTR_VAL_SCANNER _TEXT("SCANNER")
#define	REGSTR_VAL_FLOPPY	_TEXT("FLOPPY")
#define	REGSTR_VAL_SCSITID _TEXT("SCSITargetID")
#define	REGSTR_VAL_SCSILUN _TEXT("SCSILUN")
#define	REGSTR_VAL_REVLEVEL _TEXT("RevisionLevel")
#define	REGSTR_VAL_PRODUCTID _TEXT("ProductId")
#define	REGSTR_VAL_PRODUCTTYPE _TEXT("ProductType")
#define	REGSTR_VAL_DEVTYPE _TEXT("DeviceType")
#define	REGSTR_VAL_REMOVABLE _TEXT("Removable")
#define REGSTR_VAL_CURDRVLET _TEXT("CurrentDriveLetterAssignment")
#define	REGSTR_VAL_USRDRVLET _TEXT("UserDriveLetterAssignment")
#define	REGSTR_VAL_SYNCDATAXFER _TEXT("SyncDataXfer")
#define	REGSTR_VAL_AUTOINSNOTE	_TEXT("AutoInsertNotification")
#define	REGSTR_VAL_DISCONNECT _TEXT("Disconnect")
#define	REGSTR_VAL_INT13 _TEXT("Int13")
#define	REGSTR_VAL_PMODE_INT13 _TEXT("PModeInt13")
#define	REGSTR_VAL_USERSETTINGS _TEXT("AdapterSettings")
#define	REGSTR_VAL_NOIDE _TEXT("NoIDE")
#define	REGSTR_VAL_DISKCLASSNAME	_TEXT("DiskDrive")
#define	REGSTR_VAL_CDROMCLASSNAME	_TEXT("CDROM")
#define	REGSTR_VAL_FORCELOAD	_TEXT("ForceLoadPD")
#define	REGSTR_VAL_FORCEFIFO _TEXT("ForceFIFO")
#define	REGSTR_VAL_FORCECL _TEXT("ForceChangeLine")
#define REGSTR_VAL_NOUSECLASS _TEXT("NoUseClass")
#define REGSTR_VAL_NOINSTALLCLASS _TEXT("NoInstallClass")
#define REGSTR_VAL_NODISPLAYCLASS _TEXT("NoDisplayClass")
#define REGSTR_VAL_SILENTINSTALL _TEXT("SilentInstall")
#define REGSTR_KEY_PCMCIA_CLASS _TEXT("PCMCIA")
#define REGSTR_KEY_SCSI_CLASS _TEXT("SCSIAdapter")
#define REGSTR_KEY_PORTS_CLASS _TEXT("ports")
#define REGSTR_KEY_MEDIA_CLASS _TEXT("MEDIA")
#define REGSTR_KEY_DISPLAY_CLASS _TEXT("Display")
#define REGSTR_KEY_KEYBOARD_CLASS _TEXT("Keyboard")
#define REGSTR_KEY_MOUSE_CLASS _TEXT("Mouse")
#define REGSTR_KEY_MONITOR_CLASS _TEXT("Monitor")
#define REGSTR_VAL_PCMCIA_OPT	_TEXT("Options")
#define PCMCIA_OPT_HAVE_SOCKET	1
#define PCMCIA_OPT_AUTOMEM	4
#define PCMCIA_OPT_NO_SOUND	8
#define PCMCIA_OPT_NO_AUDIO	16
#define PCMCIA_OPT_NO_APMREMOVE 32
#define REGSTR_VAL_PCMCIA_MEM	_TEXT("Memory")
#define PCMCIA_DEF_MEMBEGIN	0xC0000
#define PCMCIA_DEF_MEMEND	0xFFFFFF
#define PCMCIA_DEF_MEMLEN	0x1000
#define REGSTR_VAL_PCMCIA_ALLOC _TEXT("AllocMemWin")
#define REGSTR_VAL_PCMCIA_ATAD	_TEXT("ATADelay")
#define REGSTR_VAL_PCMCIA_SIZ	_TEXT("MinRegionSize")
#define PCMCIA_DEF_MIN_REGION	0x10000
#define REGSTR_VAL_P1284MDL _TEXT("Model")
#define REGSTR_VAL_P1284MFG _TEXT("Manufacturer")
#define	REGSTR_VAL_ISAPNP	_TEXT("ISAPNP")
#define	REGSTR_VAL_ISAPNP_RDP_OVERRIDE	_TEXT("RDPOverRide")
#define	REGSTR_VAL_PCI	_TEXT("PCI")
#define	REGSTR_PCI_OPTIONS	_TEXT("Options")
#define	REGSTR_PCI_DUAL_IDE	_TEXT("PCIDualIDE")
#define	PCI_OPTIONS_USE_BIOS	1
#define	PCI_OPTIONS_USE_IRQ_STEERING	2
#define	PCI_FLAG_NO_VIDEO_IRQ	1
#define	PCI_FLAG_PCMCIA_WANT_IRQ	2
#define	PCI_FLAG_DUAL_IDE	4
#define	PCI_FLAG_NO_ENUM_AT_ALL	8
#define	PCI_FLAG_ENUM_NO_RESOURCE	16
#define	PCI_FLAG_NEED_DWORD_ACCESS	32
#define	PCI_FLAG_SINGLE_FUNCTION	64
#define	PCI_FLAG_ALWAYS_ENABLED	128
#define	PCI_FLAG_IS_IDE	256
#define	PCI_FLAG_IS_VIDEO	512
#define	PCI_FLAG_FAIL_START	1024
#define REGSTR_KEY_CRASHES	_TEXT("Crashes")
#define REGSTR_KEY_DANGERS	_TEXT("Dangers")
#define REGSTR_KEY_DETMODVARS	_TEXT("DetModVars")
#define REGSTR_KEY_NDISINFO	_TEXT("NDISInfo")
#define REGSTR_VAL_PROTINIPATH	_TEXT("ProtIniPath")
#define REGSTR_VAL_RESOURCES	_TEXT("Resources")
#define REGSTR_VAL_CRASHFUNCS	_TEXT("CrashFuncs")
#define REGSTR_VAL_CLASS	_TEXT("Class")
#define REGSTR_VAL_DEVDESC	_TEXT("DeviceDesc")
#define REGSTR_VAL_BOOTCONFIG	_TEXT("BootConfig")
#define REGSTR_VAL_DETFUNC	_TEXT("DetFunc")
#define REGSTR_VAL_DETFLAGS	_TEXT("DetFlags")
#define REGSTR_VAL_COMPATIBLEIDS _TEXT("CompatibleIDs")
#define REGSTR_VAL_DETCONFIG	_TEXT("DetConfig")
#define REGSTR_VAL_VERIFYKEY	_TEXT("VerifyKey")
#define REGSTR_VAL_COMINFO	_TEXT("ComInfo")
#define REGSTR_VAL_INFNAME	_TEXT("InfName")
#define REGSTR_VAL_CARDSPECIFIC	_TEXT("CardSpecific")
#define REGSTR_VAL_NETOSTYPE	_TEXT("NetOSType")
#define REGSTR_DATA_NETOS_NDIS	_TEXT("NDIS")
#define REGSTR_DATA_NETOS_ODI	_TEXT("ODI")
#define REGSTR_DATA_NETOS_IPX	_TEXT("IPX")
#define REGSTR_VAL_MFG _TEXT("Mfg")
#define REGSTR_VAL_SCAN_ONLY_FIRST	_TEXT("ScanOnlyFirstDrive")
#define REGSTR_VAL_SHARE_IRQ	_TEXT("ForceIRQSharing")
#define REGSTR_VAL_NONSTANDARD_ATAPI	_TEXT("NonStandardATAPI")
#define REGSTR_VAL_IDE_FORCE_SERIALIZE	_TEXT("ForceSerialization")
#define	REGSTR_VAL_MAX_HCID_LEN	1024
#define REGSTR_VAL_HWREV _TEXT("HWRevision")
#define REGSTR_VAL_ENABLEINTS _TEXT("EnableInts")
#define REGDF_NOTDETIO	1
#define REGDF_NOTDETMEM 2
#define REGDF_NOTDETIRQ 4
#define REGDF_NOTDETDMA 8
#define REGDF_NOTDETALL	(REGDF_NOTDETIO | REGDF_NOTDETMEM | REGDF_NOTDETIRQ | REGDF_NOTDETDMA)
#define REGDF_NEEDFULLCONFIG	16
#define REGDF_GENFORCEDCONFIG	32
#define REGDF_NODETCONFIG	0x8000
#define REGDF_CONFLICTIO	0x10000
#define REGDF_CONFLICTMEM	0x20000
#define REGDF_CONFLICTIRQ	0x40000
#define REGDF_CONFLICTDMA	0x80000
#define	REGDF_CONFLICTALL	(REGDF_CONFLICTIO | REGDF_CONFLICTMEM | REGDF_CONFLICTIRQ | REGDF_CONFLICTDMA)
#define REGDF_MAPIRQ2TO9	0x100000
#define REGDF_NOTVERIFIED	0x80000000
#define REGSTR_VAL_APMBIOSVER	_TEXT("APMBiosVer")
#define REGSTR_VAL_APMFLAGS	_TEXT("APMFlags")
#define REGSTR_VAL_SLSUPPORT	_TEXT("SLSupport")
#define REGSTR_VAL_MACHINETYPE	_TEXT("MachineType")
#define REGSTR_VAL_SETUPMACHINETYPE _TEXT("SetupMachineType")
#define REGSTR_MACHTYPE_UNKNOWN _TEXT("Unknown")
#define REGSTR_MACHTYPE_IBMPC	_TEXT("IBM PC")
#define REGSTR_MACHTYPE_IBMPCJR _TEXT("IBM PCjr")
#define REGSTR_MACHTYPE_IBMPCCONV	_TEXT("IBM PC Convertible")
#define REGSTR_MACHTYPE_IBMPCXT _TEXT("IBM PC/XT")
#define REGSTR_MACHTYPE_IBMPCXT_286	_TEXT("IBM PC/XT 286")
#define REGSTR_MACHTYPE_IBMPCAT _TEXT("IBM PC/AT")
#define REGSTR_MACHTYPE_IBMPS2_25	_TEXT("IBM PS/2-25")
#define REGSTR_MACHTYPE_IBMPS2_30_286	_TEXT("IBM PS/2-30 286")
#define REGSTR_MACHTYPE_IBMPS2_30	_TEXT("IBM PS/2-30")
#define REGSTR_MACHTYPE_IBMPS2_50	_TEXT("IBM PS/2-50")
#define REGSTR_MACHTYPE_IBMPS2_50Z	_TEXT("IBM PS/2-50Z")
#define REGSTR_MACHTYPE_IBMPS2_55SX	_TEXT("IBM PS/2-55SX")
#define REGSTR_MACHTYPE_IBMPS2_60	_TEXT("IBM PS/2-60")
#define REGSTR_MACHTYPE_IBMPS2_65SX	_TEXT("IBM PS/2-65SX")
#define REGSTR_MACHTYPE_IBMPS2_70	_TEXT("IBM PS/2-70")
#define REGSTR_MACHTYPE_IBMPS2_P70	_TEXT("IBM PS/2-P70")
#define REGSTR_MACHTYPE_IBMPS2_70_80	_TEXT("IBM PS/2-70/80")
#define REGSTR_MACHTYPE_IBMPS2_80	_TEXT("IBM PS/2-80")
#define REGSTR_MACHTYPE_IBMPS2_90	_TEXT("IBM PS/2-90")
#define REGSTR_MACHTYPE_IBMPS1	_TEXT("IBM PS/1")
#define REGSTR_MACHTYPE_PHOENIX_PCAT	_TEXT("Phoenix PC/AT Compatible")
#define REGSTR_MACHTYPE_HP_VECTRA	_TEXT("HP Vectra")
#define REGSTR_MACHTYPE_ATT_PC	_TEXT("AT&T PC")
#define REGSTR_MACHTYPE_ZENITH_PC	_TEXT("Zenith PC")
#define REGSTR_VAL_APMMENUSUSPEND	_TEXT("APMMenuSuspend")
#define APMMENUSUSPEND_DISABLED 0
#define APMMENUSUSPEND_ENABLED	1
#define APMMENUSUSPEND_UNDOCKED 2
#define APMMENUSUSPEND_NOCHANGE 128
#define REGSTR_VAL_BUSTYPE _TEXT("BusType")
#define REGSTR_VAL_CPU _TEXT("CPU")
#define REGSTR_VAL_NDP _TEXT("NDP")
#define REGSTR_VAL_PNPBIOSVER _TEXT("PnPBIOSVer")
#define REGSTR_VAL_PNPSTRUCOFFSET _TEXT("PnPStrucOffset")
#define REGSTR_VAL_PCIBIOSVER _TEXT("PCIBIOSVer")
#define REGSTR_VAL_HWMECHANISM _TEXT("HWMechanism")
#define REGSTR_VAL_LASTPCIBUSNUM _TEXT("LastPCIBusNum")
#define REGSTR_VAL_CONVMEM _TEXT("ConvMem")
#define REGSTR_VAL_EXTMEM _TEXT("ExtMem")
#define REGSTR_VAL_COMPUTERNAME _TEXT("ComputerName")
#define REGSTR_VAL_BIOSNAME _TEXT("BIOSName")
#define REGSTR_VAL_BIOSVERSION _TEXT("BIOSVersion")
#define REGSTR_VAL_BIOSDATE _TEXT("BIOSDate")
#define REGSTR_VAL_MODEL _TEXT("Model")
#define REGSTR_VAL_SUBMODEL _TEXT("Submodel")
#define REGSTR_VAL_REVISION _TEXT("Revision")
#define REGSTR_VAL_FIFODEPTH	_TEXT("FIFODepth")
#define REGSTR_VAL_RDINTTHRESHOLD	_TEXT("RDIntThreshold")
#define REGSTR_VAL_WRINTTHRESHOLD	_TEXT("WRIntThreshold")
#define REGSTR_VAL_PRIORITY	_TEXT("Priority")
#define REGSTR_VAL_DRIVER	_TEXT("Driver")
#define REGSTR_VAL_FUNCDESC	_TEXT("FunctionDesc")
#define REGSTR_VAL_FORCEDCONFIG _TEXT("ForcedConfig")
#define REGSTR_VAL_CONFIGFLAGS	_TEXT("ConfigFlags")
#define REGSTR_VAL_CSCONFIGFLAGS _TEXT("CSConfigFlags")
#define CONFIGFLAG_DISABLED	1
#define CONFIGFLAG_REMOVED	2
#define CONFIGFLAG_MANUAL_INSTALL 4
#define CONFIGFLAG_IGNORE_BOOT_LC 8
#define CONFIGFLAG_NET_BOOT	16
#define CONFIGFLAG_REINSTALL	32
#define CONFIGFLAG_FAILEDINSTALL	64
#define CONFIGFLAG_CANTSTOPACHILD	128
#define CONFIGFLAG_OKREMOVEROM	256
#define CONFIGFLAG_NOREMOVEEXIT	512
#define CSCONFIGFLAG_BITS	7
#define CSCONFIGFLAG_DISABLED	1
#define CSCONFIGFLAG_DO_NOT_CREATE	2
#define CSCONFIGFLAG_DO_NOT_START	4
#define DMSTATEFLAG_APPLYTOALL 1
#define	REGSTR_VAL_ROOT_DEVNODE	_TEXT("HTREE\\ROOT\\0")
#define	REGSTR_VAL_RESERVED_DEVNODE	_TEXT("HTREE\\RESERVED\\0")
#define	REGSTR_PATH_READDATAPORT	REGSTR_KEY_ISAENUM _TEXT("\\ReadDataPort\\0")
#define	REGSTR_PATH_MULTI_FUNCTION	_TEXT("MF")
#define	REGSTR_VAL_RESOURCE_MAP	_TEXT("ResourceMap")
#define	REGSTR_PATH_CHILD_PREFIX	_TEXT("Child")
#define	NUM_RESOURCE_MAP	256
#define	REGSTR_VAL_MF_FLAGS	_TEXT("MFFlags")
#define	MF_FLAGS_EVEN_IF_NO_RESOURCE	1
#define	MF_FLAGS_NO_CREATE_IF_NO_RESOURCE	2
#define	MF_FLAGS_FILL_IN_UNKNOWN_RESOURCE	4
#define	MF_FLAGS_CREATE_BUT_NO_SHOW_DISABLED	8
#define	EISAFLAG_NO_IO_MERGE	1
#define	EISAFLAG_SLOT_IO_FIRST	2
#define	EISA_NO_MAX_FUNCTION	0xFF
#define	NUM_EISA_RANGES	4
#define REGSTR_VAL_DRVDESC	_TEXT("DriverDesc")
#define REGSTR_VAL_DEVLOADER	_TEXT("DevLoader")
#define REGSTR_VAL_STATICVXD	_TEXT("StaticVxD")
#define REGSTR_VAL_PROPERTIES	_TEXT("Properties")
#define REGSTR_VAL_MANUFACTURER _TEXT("Manufacturer")
#define REGSTR_VAL_EXISTS	_TEXT("Exists")
#define REGSTR_VAL_CMENUMFLAGS	_TEXT("CMEnumFlags")
#define REGSTR_VAL_CMDRIVFLAGS	_TEXT("CMDrivFlags")
#define	REGSTR_VAL_ENUMERATOR	_TEXT("Enumerator")
#define	REGSTR_VAL_DEVICEDRIVER	_TEXT("DeviceDriver")
#define REGSTR_VAL_PORTNAME	_TEXT("PortName")
#define REGSTR_VAL_INFPATH _TEXT("InfPath")
#define REGSTR_VAL_INFSECTION	_TEXT("InfSection")
#define REGSTR_VAL_POLLING	_TEXT("Polling")
#define REGSTR_VAL_DONTLOADIFCONFLICT _TEXT("DontLoadIfConflict")
#define REGSTR_VAL_PORTSUBCLASS _TEXT("PortSubClass")
#define REGSTR_VAL_NETCLEAN _TEXT("NetClean")
#define REGSTR_VAL_IDE_NO_SERIALIZE _TEXT("IDENoSerialize")
#define REGSTR_VAL_NOCMOSORFDPT _TEXT("NoCMOSorFDPT")
#define REGSTR_VAL_COMVERIFYBASE _TEXT("COMVerifyBase")
#define REGSTR_KEY_OVERRIDE	_TEXT("Override")
#define	REGSTR_VAL_CONFIGMG	_TEXT("CONFIGMG")
#define REGSTR_VAL_SYSDM	_TEXT("SysDM")
#define REGSTR_VAL_SYSDMFUNC	_TEXT("SysDMFunc")
#define	REGSTR_VAL_PRIVATE	_TEXT("Private")
#define	REGSTR_VAL_PRIVATEFUNC	_TEXT("PrivateFunc")
#define	REGSTR_VAL_DETECT	_TEXT("Detect")
#define	REGSTR_VAL_DETECTFUNC	_TEXT("DetectFunc")
#define	REGSTR_VAL_ASKFORCONFIG	_TEXT("AskForConfig")
#define	REGSTR_VAL_ASKFORCONFIGFUNC _TEXT("AskForConfigFunc")
#define	REGSTR_VAL_WAITFORUNDOCK _TEXT("WaitForUndock")
#define	REGSTR_VAL_WAITFORUNDOCKFUNC _TEXT("WaitForUndockFunc")
#define	REGSTR_VAL_REMOVEROMOKAY _TEXT("RemoveRomOkay")
#define	REGSTR_VAL_REMOVEROMOKAYFUNC _TEXT("RemoveRomOkayFunc")
#define REGSTR_VAL_CURCONFIG	_TEXT("CurrentConfig")
#define REGSTR_VAL_FRIENDLYNAME _TEXT("FriendlyName")
#define REGSTR_VAL_CURRENTCONFIG _TEXT("CurrentConfig")
#define REGSTR_VAL_MAP	_TEXT("Map")
#define REGSTR_VAL_ID	_TEXT("CurrentID")
#define REGSTR_VAL_DOCKED	_TEXT("CurrentDockedState")
#define REGSTR_VAL_CHECKSUM	_TEXT("CurrentChecksum")
#define REGSTR_VAL_HWDETECT	_TEXT("HardwareDetect")
#define REGSTR_VAL_INHIBITRESULTS _TEXT("InhibitResults")
#define REGSTR_VAL_PROFILEFLAGS _TEXT("ProfileFlags")
#define REGSTR_KEY_PCMCIA	_TEXT("PCMCIA\\")
#define REGSTR_KEY_PCUNKNOWN	_TEXT("UNKNOWN_MANUFACTURER")
#define REGSTR_VAL_PCSSDRIVER	_TEXT("Driver")
#define REGSTR_KEY_PCMTD	_TEXT("MTD-")
#define REGSTR_VAL_PCMTDRIVER	_TEXT("MTD")
#define REGSTR_VAL_HARDWAREID	_TEXT("HardwareID")
#define REGSTR_VAL_INSTALLER	_TEXT("Installer")
#define REGSTR_VAL_INSICON	_TEXT("Icon")
#define REGSTR_VAL_ENUMPROPPAGES _TEXT("EnumPropPages")
#define REGSTR_VAL_BASICPROPERTIES _TEXT("BasicProperties")
#define REGSTR_VAL_PRIVATEPROBLEM _TEXT("PrivateProblem")
#define REGSTR_KEY_CURRENT	_TEXT("Current")
#define REGSTR_KEY_DEFAULT	_TEXT("Default")
#define REGSTR_KEY_MODES	_TEXT("Modes")
#define REGSTR_VAL_MODE _TEXT("Mode")
#define REGSTR_VAL_BPP	_TEXT("BPP")
#define REGSTR_VAL_HRES _TEXT("HRes")
#define REGSTR_VAL_VRES _TEXT("VRes")
#define REGSTR_VAL_FONTSIZE	_TEXT("FontSize")
#define REGSTR_VAL_DRV	_TEXT("drv")
#define REGSTR_VAL_GRB	_TEXT("grb")
#define REGSTR_VAL_VDD	_TEXT("vdd")
#define REGSTR_VAL_VER	_TEXT("Ver")
#define REGSTR_VAL_MAXRES	_TEXT("MaxResolution")
#define REGSTR_VAL_DPMS _TEXT("DPMS")
#define REGSTR_VAL_RESUMERESET _TEXT("ResumeReset")
#define REGSTR_VAL_DESCRIPTION _TEXT("Description")
#define REGSTR_KEY_SYSTEM	_TEXT("System")
#define REGSTR_KEY_USER _TEXT("User")
#define REGSTR_VAL_DPI	_TEXT("dpi")
#define REGSTR_VAL_PCICOPTIONS	_TEXT("PCICOptions")
#ifndef NEC_98
#define PCIC_DEFAULT_IRQMASK	0x4EB8
#else
#define PCIC_DEFAULT_IRQMASK	0x1468
#endif
#define PCIC_DEFAULT_NUMSOCKETS 0
#define REGSTR_VAL_PCICIRQMAP	_TEXT("PCICIRQMap")
#define REGSTR_PATH_APPEARANCE	_TEXT("Control Panel\\Appearance")
#define REGSTR_PATH_LOOKSCHEMES _TEXT("Control Panel\\Appearance\\Schemes")
#define REGSTR_VAL_CUSTOMCOLORS _TEXT("CustomColors")
#define REGSTR_PATH_SCREENSAVE _TEXT("Control Panel\\Desktop")
#define REGSTR_VALUE_USESCRPASSWORD _TEXT("ScreenSaveUsePassword")
#define REGSTR_VALUE_SCRPASSWORD _TEXT("ScreenSave_Data")
#define REGSTR_VALUE_LOWPOWERTIMEOUT	_TEXT("ScreenSaveLowPowerTimeout")
#define REGSTR_VALUE_POWEROFFTIMEOUT	_TEXT("ScreenSavePowerOffTimeout")
#define REGSTR_VALUE_LOWPOWERACTIVE	_TEXT("ScreenSaveLowPowerActive")
#define REGSTR_VALUE_POWEROFFACTIVE	_TEXT("ScreenSavePowerOffActive")
#define REGSTR_PATH_WINDOWSAPPLETS _TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\Applets")
#define REGSTR_PATH_SYSTRAY _TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\Applets\\SysTray")
#define REGSTR_VAL_SYSTRAYSVCS _TEXT("Services")
#define REGSTR_VAL_SYSTRAYBATFLAGS _TEXT("PowerFlags")
#define REGSTR_VAL_SYSTRAYPCCARDFLAGS _TEXT("PCMCIAFlags")
#define REGSTR_PATH_NETWORK_USERSETTINGS	_TEXT("Network")
#define REGSTR_KEY_NETWORK_PERSISTENT	_TEXT("\\Persistent")
#define REGSTR_KEY_NETWORK_RECENT	_TEXT("\\Recent")
#define REGSTR_VAL_REMOTE_PATH	_TEXT("RemotePath")
#define REGSTR_VAL_USER_NAME	_TEXT("UserName")
#define REGSTR_VAL_PROVIDER_NAME	_TEXT("ProviderName")
#define REGSTR_VAL_CONNECTION_TYPE	_TEXT("ConnectionType")
#define REGSTR_VAL_UPGRADE	_TEXT("Upgrade")
#define REGSTR_KEY_LOGON _TEXT("\\Logon")
#define REGSTR_VAL_MUSTBEVALIDATED _TEXT("MustBeValidated")
#define REGSTR_VAL_RUNLOGINSCRIPT	_TEXT("ProcessLoginScript")
#define REGSTR_KEY_NETWORKPROVIDER _TEXT("\\NetworkProvider")
#define REGSTR_PATH_NW32NETPROVIDER REGSTR_PATH_SERVICES _TEXT("\\NWNP32" REGSTR_KEY_NETWORKPROVIDER
#define REGSTR_PATH_MS32NETPROVIDER REGSTR_PATH_SERVICES _TEXT("\\MSNP32" REGSTR_KEY_NETWORKPROVIDER
#define REGSTR_VAL_AUTHENT_AGENT _TEXT("AuthenticatingAgent")
#define REGSTR_VAL_PREFREDIR _TEXT("PreferredRedir")
#define REGSTR_VAL_AUTOSTART _TEXT("AutoStart")
#define REGSTR_VAL_AUTOLOGON _TEXT("AutoLogon")
#define REGSTR_VAL_NETCARD _TEXT("Netcard")
#define REGSTR_VAL_TRANSPORT _TEXT("Transport")
#define REGSTR_VAL_DYNAMIC _TEXT("Dynamic")
#define REGSTR_VAL_TRANSITION _TEXT("Transition")
#define REGSTR_VAL_STATICDRIVE _TEXT("StaticDrive")
#define REGSTR_VAL_LOADHI _TEXT("LoadHi")
#define REGSTR_VAL_LOADRMDRIVERS _TEXT("LoadRMDrivers")
#define REGSTR_VAL_SETUPN _TEXT("SetupN")
#define REGSTR_VAL_SETUPNPATH _TEXT("SetupNPath")
#define REGSTR_VAL_WRKGRP_FORCEMAPPING _TEXT("WrkgrpForceMapping")
#define REGSTR_VAL_WRKGRP_REQUIRED _TEXT("WrkgrpRequired")
#define REGSTR_PATH_CURRENT_CONTROL_SET	_TEXT("System\\CurrentControlSet\\Control")
#define REGSTR_VAL_CURRENT_USER	_TEXT("Current User")
#define REGSTR_PATH_PWDPROVIDER	_TEXT("System\\CurrentControlSet\\Control\\PwdProvider")
#define REGSTR_VAL_PWDPROVIDER_PATH _TEXT("ProviderPath")
#define REGSTR_VAL_PWDPROVIDER_DESC _TEXT("Description")
#define REGSTR_VAL_PWDPROVIDER_CHANGEPWD _TEXT("ChangePassword")
#define REGSTR_VAL_PWDPROVIDER_CHANGEPWDHWND _TEXT("ChangePasswordHwnd")
#define REGSTR_VAL_PWDPROVIDER_GETPWDSTATUS _TEXT("GetPasswordStatus")
#define REGSTR_VAL_PWDPROVIDER_ISNP _TEXT("NetworkProvider")
#define REGSTR_VAL_PWDPROVIDER_CHANGEORDER _TEXT("ChangeOrder")
#define REGSTR_PATH_POLICIES	_TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\Policies")
#define REGSTR_PATH_UPDATE	_TEXT("System\\CurrentControlSet\\Control\\Update")
#define REGSTR_VALUE_ENABLE	_TEXT("Enable")
#define REGSTR_VALUE_VERBOSE	_TEXT("Verbose")
#define REGSTR_VALUE_NETPATH	_TEXT("NetworkPath")
#define REGSTR_VALUE_DEFAULTLOC	_TEXT("UseDefaultNetLocation")
#define REGSTR_KEY_NETWORK	_TEXT("Network")
#define REGSTR_KEY_SYSTEM	_TEXT("System")
#define REGSTR_KEY_PRINTERS	_TEXT("Printers")
#define REGSTR_KEY_WINOLDAPP	_TEXT("WinOldApp")
#define REGSTR_VAL_NOFILESHARING	_TEXT("NoFileSharing")
#define REGSTR_VAL_NOPRINTSHARING	_TEXT("NoPrintSharing")
#define REGSTR_VAL_NOFILESHARINGCTRL	_TEXT("NoFileSharingControl")
#define REGSTR_VAL_NOPRINTSHARINGCTRL	_TEXT("NoPrintSharingControl")
#define REGSTR_VAL_HIDESHAREPWDS	_TEXT("HideSharePwds")
#define REGSTR_VAL_DISABLEPWDCACHING	_TEXT("DisablePwdCaching")
#define REGSTR_VAL_ALPHANUMPWDS	_TEXT("AlphanumPwds")
#define REGSTR_VAL_NETSETUP_DISABLE	_TEXT("NoNetSetup")
#define REGSTR_VAL_NETSETUP_NOCONFIGPAGE	_TEXT("NoNetSetupConfigPage")
#define REGSTR_VAL_NETSETUP_NOIDPAGE	_TEXT("NoNetSetupIDPage")
#define REGSTR_VAL_NETSETUP_NOSECURITYPAGE	_TEXT("NoNetSetupSecurityPage")
#define REGSTR_VAL_SYSTEMCPL_NOVIRTMEMPAGE _TEXT("NoVirtMemPage")
#define REGSTR_VAL_SYSTEMCPL_NODEVMGRPAGE _TEXT("NoDevMgrPage")
#define REGSTR_VAL_SYSTEMCPL_NOCONFIGPAGE	_TEXT("NoConfigPage")
#define REGSTR_VAL_SYSTEMCPL_NOFILESYSPAGE	_TEXT("NoFileSysPage")
#define REGSTR_VAL_DISPCPL_NODISPCPL	_TEXT("NoDispCPL")
#define REGSTR_VAL_DISPCPL_NOBACKGROUNDPAGE _TEXT("NoDispBackgroundPage")
#define REGSTR_VAL_DISPCPL_NOSCRSAVPAGE _TEXT("NoDispScrSavPage")
#define REGSTR_VAL_DISPCPL_NOAPPEARANCEPAGE _TEXT("NoDispAppearancePage")
#define REGSTR_VAL_DISPCPL_NOSETTINGSPAGE _TEXT("NoDispSettingsPage")
#define REGSTR_VAL_SECCPL_NOSECCPL	_TEXT("NoSecCPL")
#define REGSTR_VAL_SECCPL_NOPWDPAGE	_TEXT("NoPwdPage")
#define REGSTR_VAL_SECCPL_NOADMINPAGE	_TEXT("NoAdminPage")
#define REGSTR_VAL_SECCPL_NOPROFILEPAGE	_TEXT("NoProfilePage")
#define REGSTR_VAL_PRINTERS_HIDETABS	_TEXT("NoPrinterTabs")
#define REGSTR_VAL_PRINTERS_NODELETE	_TEXT("NoDeletePrinter")
#define REGSTR_VAL_PRINTERS_NOADD	_TEXT("NoAddPrinter")
#define REGSTR_VAL_WINOLDAPP_DISABLED	_TEXT("Disabled")
#define REGSTR_VAL_WINOLDAPP_NOREALMODE	_TEXT("NoRealMode")
#define REGSTR_VAL_NOENTIRENETWORK	_TEXT("NoEntireNetwork")
#define REGSTR_VAL_NOWORKGROUPCONTENTS	_TEXT("NoWorkgroupContents")
#define REGSTR_VAL_MINPWDLEN	_TEXT("MinPwdLen")
#define REGSTR_VAL_PWDEXPIRATION	_TEXT("PwdExpiration")
#define REGSTR_VAL_WIN31PROVIDER	_TEXT("Win31Provider")
#define REGSTR_VAL_DISABLEREGTOOLS	_TEXT("DisableRegistryTools")
#define REGSTR_PATH_WINLOGON	_TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\Winlogon")
#define REGSTR_VAL_LEGALNOTICECAPTION	_TEXT("LegalNoticeCaption")
#define REGSTR_VAL_LEGALNOTICETEXT	_TEXT("LegalNoticeText")
#define REGSTR_VAL_RESTRICTRUN	_TEXT("RestrictRun")
#define REGSTR_KEY_POL_USERS	_TEXT("Users")
#define REGSTR_KEY_POL_COMPUTERS	_TEXT("Computers")
#define REGSTR_KEY_POL_USERGROUPS	_TEXT("UserGroups")
#define REGSTR_KEY_POL_DEFAULT	_TEXT(".default")
#define REGSTR_KEY_POL_USERGROUPDATA _TEXT("GroupData\\UserGroups\\Priority")
#define REGSTR_PATH_TIMEZONE	_TEXT("System\\CurrentControlSet\\Control\\TimeZoneInformation")
#define REGSTR_VAL_TZBIAS	_TEXT("Bias")
#define REGSTR_VAL_TZDLTBIAS	_TEXT("DaylightBias")
#define REGSTR_VAL_TZSTDBIAS	_TEXT("StandardBias")
#define REGSTR_VAL_TZACTBIAS	_TEXT("ActiveTimeBias")
#define REGSTR_VAL_TZDLTFLAG	_TEXT("DaylightFlag")
#define REGSTR_VAL_TZSTDSTART	_TEXT("StandardStart")
#define REGSTR_VAL_TZDLTSTART	_TEXT("DaylightStart")
#define REGSTR_VAL_TZDLTNAME	_TEXT("DaylightName")
#define REGSTR_VAL_TZSTDNAME	_TEXT("StandardName")
#define REGSTR_VAL_TZNOCHANGESTART _TEXT("NoChangeStart")
#define REGSTR_VAL_TZNOCHANGEEND _TEXT("NoChangeEnd")
#define REGSTR_VAL_TZNOAUTOTIME _TEXT("DisableAutoDaylightTimeSet")
#define REGSTR_PATH_FLOATINGPOINTPROCESSOR _TEXT("HARDWARE\\DESCRIPTION\\System\\FloatingPointProcessor")
#define REGSTR_PATH_FLOATINGPOINTPROCESSOR0 _TEXT("HARDWARE\\DESCRIPTION\\System\\FloatingPointProcessor\\0")
#define REGSTR_PATH_COMPUTRNAME _TEXT("System\\CurrentControlSet\\Control\\ComputerName\\ComputerName")
#define REGSTR_VAL_COMPUTRNAME _TEXT("ComputerName")
#define REGSTR_PATH_SHUTDOWN _TEXT("System\\CurrentControlSet\\Control\\Shutdown")
#define REGSTR_VAL_FORCEREBOOT _TEXT("ForceReboot")
#define REGSTR_VAL_SETUPPROGRAMRAN _TEXT("SetupProgramRan")
#define REGSTR_VAL_DOES_POLLING _TEXT("PollingSupportNeeded")
#define REGSTR_PATH_KNOWNDLLS	_TEXT("System\\CurrentControlSet\\Control\\SessionManager\\KnownDLLs")
#define REGSTR_PATH_KNOWN16DLLS	_TEXT("System\\CurrentControlSet\\Control\\SessionManager\\Known16DLLs")
#define REGSTR_PATH_CHECKVERDLLS _TEXT("System\\CurrentControlSet\\Control\\SessionManager\\CheckVerDLLs")
#define REGSTR_PATH_WARNVERDLLS _TEXT("System\\CurrentControlSet\\Control\\SessionManager\\WarnVerDLLs")
#define REGSTR_PATH_HACKINIFILE _TEXT("System\\CurrentControlSet\\Control\\SessionManager\\HackIniFiles")
#define REGSTR_PATH_CHECKBADAPPS _TEXT("System\\CurrentControlSet\\Control\\SessionManager\\CheckBadApps")
#define REGSTR_PATH_APPPATCH _TEXT("System\\CurrentControlSet\\Control\\SessionManager\\AppPatches")
#define REGSTR_PATH_KNOWNVXDS	_TEXT("System\\CurrentControlSet\\Control\\SessionManager\\KnownVxDs")
#define REGSTR_VAL_UNINSTALLER_DISPLAYNAME _TEXT("DisplayName")
#define REGSTR_VAL_UNINSTALLER_COMMANDLINE _TEXT("UninstallString")
#define REGSTR_PATH_DESKTOP	REGSTR_PATH_SCREENSAVE
#define REGSTR_PATH_MOUSE	_TEXT("Control Panel\\Mouse")
#define REGSTR_PATH_KEYBOARD _TEXT("Control Panel\\Keyboard")
#define REGSTR_PATH_COLORS	_TEXT("Control Panel\\Colors")
#define REGSTR_PATH_SOUND	_TEXT("Control Panel\\Sound")
#define REGSTR_PATH_METRICS	_TEXT("Control Panel\\Desktop\\WindowMetrics")
#define REGSTR_PATH_ICONS _TEXT("Control Panel\\Icons")
#define REGSTR_PATH_CURSORS _TEXT("Control Panel\\Cursors")
#define REGSTR_PATH_CHECKDISK	_TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\Applets\\Check Drive")
#define REGSTR_PATH_CHECKDISKSET _TEXT("Settings")
#define REGSTR_PATH_CHECKDISKUDRVS _TEXT("NoUnknownDDErrDrvs")
#define REGSTR_PATH_FAULT	_TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\Fault")
#define REGSTR_VAL_FAULT_LOGFILE	_TEXT("LogFile")
#define	REGSTR_PATH_AEDEBUG	_TEXT("Software\\Microsoft\\Windows NT\\CurrentVersion\\AeDebug")
#define REGSTR_VAL_AEDEBUG_DEBUGGER	_TEXT("Debugger")
#define REGSTR_VAL_AEDEBUG_AUTO	_TEXT("Auto")
#define REGSTR_PATH_GRPCONV	_TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\GrpConv")
#define REGSTR_VAL_REGITEMDELETEMESSAGE _TEXT("Removal Message")
#define REGSTR_PATH_LASTCHECK	_TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\LastCheck")
#define REGSTR_PATH_LASTOPTIMIZE	_TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\LastOptimize")
#define REGSTR_PATH_LASTBACKUP	_TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\LastBackup")
#define REGSTR_PATH_CHKLASTCHECK	_TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\Applets\\Check Drive\\LastCheck")
#define REGSTR_PATH_CHKLASTSURFAN	_TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\Applets\\Check Drive\\LastSurfaceAnalysis")
#define DTRESULTOK	0
#define DTRESULTFIX	1
#define DTRESULTPROB	2
#define DTRESULTPART	3
#define REGSTR_KEY_SHARES	_TEXT("Software\\Microsoft\\Windows\\CurrentVersion\\Network\\LanMan")
#define REGSTR_VAL_SHARES_FLAGS _TEXT("Flags")
#define REGSTR_VAL_SHARES_TYPE _TEXT("Type")
#define REGSTR_VAL_SHARES_PATH _TEXT("Path")
#define REGSTR_VAL_SHARES_REMARK _TEXT("Remark")
#define REGSTR_VAL_SHARES_RW_PASS _TEXT("Parm1")
#define REGSTR_VAL_SHARES_RO_PASS _TEXT("Parm2")
#define REGSTR_PATH_PRINT _TEXT("System\\CurrentControlSet\\Control\\Print")
#define REGSTR_PATH_PRINTERS _TEXT("System\\CurrentControlSet\\Control\\Print\\Printers")
#define REGSTR_PATH_PROVIDERS _TEXT("System\\CurrentControlSet\\Control\\Print\\Providers")
#define REGSTR_PATH_MONITORS _TEXT("System\\CurrentControlSet\\Control\\Print\\Monitors")
#define REGSTR_PATH_ENVIRONMENTS _TEXT("System\\CurrentControlSet\\Control\\Print\\Environments")
#define REGSTR_VAL_START_ON_BOOT _TEXT("StartOnBoot")
#define REGSTR_VAL_PRINTERS_MASK _TEXT("PrintersMask")
#define REGSTR_VAL_DOS_SPOOL_MASK _TEXT("DOSSpoolMask")
#define REGSTR_KEY_CURRENT_ENV _TEXT("\\Windows 4.0")
#define REGSTR_KEY_DRIVERS _TEXT("\\Drivers")
#define REGSTR_KEY_PRINT_PROC _TEXT("\\Print Processors")
#define REGSTR_PATH_EVENTLABELS _TEXT("AppEvents\\EventLabels")
#define REGSTR_PATH_SCHEMES _TEXT("AppEvents\\Schemes")
#define REGSTR_PATH_APPS REGSTR_PATH_SCHEMES _TEXT("\\Apps")
#define REGSTR_PATH_APPS_DEFAULT REGSTR_PATH_SCHEMES _TEXT("\\Apps\\.Default")
#define REGSTR_PATH_NAMES REGSTR_PATH_SCHEMES _TEXT("\\Names")
#define REGSTR_PATH_MULTIMEDIA REGSTR_PATH_SETUP _TEXT("\\Multimedia")
#define REGSTR_PATH_MULTIMEDIA_AUDIO _TEXT("Software\\Microsoft\\Multimedia\\Audio")
#define REGSTR_PATH_MEDIARESOURCES REGSTR_PATH_CURRENT_CONTROL_SET _TEXT("\\MediaResources")
#define REGSTR_PATH_MEDIAPROPERTIES REGSTR_PATH_CURRENT_CONTROL_SET _TEXT("\\MediaProperties")
#define REGSTR_PATH_PRIVATEPROPERTIES REGSTR_PATH_MEDIAPROPERTIES _TEXT("\\PrivateProperties")
#define REGSTR_PATH_PUBLICPROPERTIES REGSTR_PATH_MEDIAPROPERTIES _TEXT("\\PublicProperties")
#define REGSTR_PATH_JOYOEM REGSTR_PATH_PRIVATEPROPERTIES _TEXT("\\Joystick\\OEM")
#define REGSTR_PATH_JOYCONFIG REGSTR_PATH_MEDIARESOURCES _TEXT("\\Joystick")
#define REGSTR_KEY_JOYCURR _TEXT("CurrentJoystickSettings")
#define REGSTR_KEY_JOYSETTINGS _TEXT("JoystickSettings")
#define REGSTR_VAL_JOYUSERVALUES _TEXT("JoystickUserValues")
#define REGSTR_VAL_JOYCALLOUT	_TEXT("JoystickCallout")
#define REGSTR_VAL_JOYNCONFIG	_TEXT("Joystick%dConfiguration")
#define REGSTR_VAL_JOYNOEMNAME	_TEXT("Joystick%dOEMName")
#define REGSTR_VAL_JOYNOEMCALLOUT _TEXT("Joystick%dOEMCallout")
#define REGSTR_VAL_JOYOEMCALLOUT	_TEXT("OEMCallout")
#define REGSTR_VAL_JOYOEMNAME	_TEXT("OEMName")
#define REGSTR_VAL_JOYOEMDATA	_TEXT("OEMData")
#define REGSTR_VAL_JOYOEMXYLABEL	_TEXT("OEMXYLabel")
#define REGSTR_VAL_JOYOEMZLABEL	_TEXT("OEMZLabel")
#define REGSTR_VAL_JOYOEMRLABEL	_TEXT("OEMRLabel")
#define REGSTR_VAL_JOYOEMPOVLABEL	_TEXT("OEMPOVLabel")
#define REGSTR_VAL_JOYOEMULABEL	_TEXT("OEMULabel")
#define REGSTR_VAL_JOYOEMVLABEL	_TEXT("OEMVLabel")
#define REGSTR_VAL_JOYOEMTESTMOVEDESC	_TEXT("OEMTestMoveDesc")
#define REGSTR_VAL_JOYOEMTESTBUTTONDESC	_TEXT("OEMTestButtonDesc")
#define REGSTR_VAL_JOYOEMTESTMOVECAP	_TEXT("OEMTestMoveCap")
#define REGSTR_VAL_JOYOEMTESTBUTTONCAP	_TEXT("OEMTestButtonCap")
#define REGSTR_VAL_JOYOEMTESTWINCAP	_TEXT("OEMTestWinCap")
#define REGSTR_VAL_JOYOEMCALCAP	_TEXT("OEMCalCap")
#define REGSTR_VAL_JOYOEMCALWINCAP	_TEXT("OEMCalWinCap")
#define REGSTR_VAL_JOYOEMCAL1	_TEXT("OEMCal1")
#define REGSTR_VAL_JOYOEMCAL2	_TEXT("OEMCal2")
#define REGSTR_VAL_JOYOEMCAL3	_TEXT("OEMCal3")
#define REGSTR_VAL_JOYOEMCAL4	_TEXT("OEMCal4")
#define REGSTR_VAL_JOYOEMCAL5	_TEXT("OEMCal5")
#define REGSTR_VAL_JOYOEMCAL6	_TEXT("OEMCal6")
#define REGSTR_VAL_JOYOEMCAL7	_TEXT("OEMCal7")
#define REGSTR_VAL_JOYOEMCAL8	_TEXT("OEMCal8")
#define REGSTR_VAL_JOYOEMCAL9	_TEXT("OEMCal9")
#define REGSTR_VAL_JOYOEMCAL10	_TEXT("OEMCal10")
#define REGSTR_VAL_JOYOEMCAL11	_TEXT("OEMCal11")
#define REGSTR_VAL_JOYOEMCAL12	_TEXT("OEMCal12")
#ifndef NEC_98
#define REGSTR_KEY_ISAENUM	_TEXT("ISAPnP")
#define REGSTR_KEY_EISAENUM	_TEXT("EISA")
#define	REGSTR_VAL_EISA_RANGES	_TEXT("EISARanges")
#define	REGSTR_VAL_EISA_FUNCTIONS	_TEXT("EISAFunctions")
#define	REGSTR_VAL_EISA_FUNCTIONS_MASK	_TEXT("EISAFunctionsMask")
#define	REGSTR_VAL_EISA_FLAGS	_TEXT("EISAFlags")
#define	REGSTR_VAL_EISA_SIMULATE_INT15	_TEXT("EISASimulateInt15")
#else
#define REGSTR_KEY_ISAENUM	_TEXT("C98PnP")
#define REGSTR_KEY_EISAENUM	_TEXT("NESA")
#define	REGSTR_VAL_EISA_RANGES	_TEXT("NESARanges")
#define	REGSTR_VAL_EISA_FUNCTIONS	_TEXT("NESAFunctions")
#define	REGSTR_VAL_EISA_FUNCTIONS_MASK	_TEXT("NESAFunctionsMask")
#define	REGSTR_VAL_EISA_FLAGS	_TEXT("NESAFlags")
#define	REGSTR_VAL_EISA_SIMULATE_INT15	_TEXT("NESASimulateInt15")
#endif
typedef struct _DSKTLSYSTEMTIME {
	WORD wYear;
	WORD wMonth;
	WORD wDayOfWeek;
	WORD wDay;
	WORD wHour;
	WORD wMinute;
	WORD wSecond;
	WORD wMilliseconds;
	WORD wResult;
} DSKTLSYSTEMTIME,*PDSKTLSYSTEMTIME,*LPDSKTLSYSTEMTIME;
#ifdef __cplusplus
}
#endif
#endif
