LIBC_CHEWOUT_FILES += \
	%D%/closer.def \
	%D%/reent.def \
	%D%/execr.def \
	%D%/fcntlr.def \
	%D%/fstatr.def \
	%D%/gettimeofdayr.def \
	%D%/linkr.def \
	%D%/lseekr.def \
	%D%/mkdirr.def \
	%D%/openr.def \
	%D%/readr.def \
	%D%/renamer.def \
	%D%/signalr.def \
	%D%/sbrkr.def \
	%D%/statr.def \
	%D%/timesr.def \
	%D%/unlinkr.def \
	%D%/fstat64r.def \
	%D%/lseek64r.def \
	%D%/stat64r.def \
	%D%/open64r.def \
	%D%/writer.def

LIBC_CHAPTERS += %D%/reent.tex
