LIBC_CHEWOUT_FILES += \
	%D%/isalnum.def \
	%D%/isalpha.def \
	%D%/isascii.def \
	%D%/isblank.def \
	%D%/iscntrl.def \
	%D%/isdigit.def \
	%D%/islower.def \
	%D%/isprint.def \
	%D%/ispunct.def \
	%D%/isspace.def \
	%D%/isupper.def \
	%D%/iswalnum.def \
	%D%/iswalpha.def \
	%D%/iswblank.def \
	%D%/iswcntrl.def \
	%D%/iswctype.def \
	%D%/iswdigit.def \
	%D%/iswgraph.def \
	%D%/iswlower.def \
	%D%/iswprint.def \
	%D%/iswpunct.def \
	%D%/iswspace.def \
	%D%/iswupper.def \
	%D%/iswxdigit.def \
	%D%/isxdigit.def \
	%D%/toascii.def \
	%D%/tolower.def \
	%D%/toupper.def \
	%D%/towctrans.def \
	%D%/towlower.def \
	%D%/towupper.def \
	%D%/wctrans.def \
	%D%/wctype.def

LIBC_CHAPTERS += %D%/ctype.tex
