LIBM_CHEWOUT_FILES += \
	%D%/feclearexcept.def %D%/fegetenv.def \
	%D%/fegetexceptflag.def %D%/fegetround.def %D%/feholdexcept.def \
	%D%/feraiseexcept.def %D%/fesetenv.def %D%/fesetexceptflag.def %D%/fesetround.def \
	%D%/fetestexcept.def %D%/feupdateenv.def

LIBM_CHAPTERS += %D%/fenv.tex
