LIBC_CHEWOUT_FILES += \
	%D%/asctime.def \
	%D%/clock.def \
	%D%/ctime.def \
	%D%/difftime.def \
	%D%/gmtime.def \
	%D%/lcltime.def \
	%D%/mktime.def \
	%D%/strftime.def \
	%D%/time.def \
	%D%/tzlock.def \
	%D%/tzset.def \
	%D%/wcsftime.def

LIBC_CHAPTERS += %D%/time.tex
