#
# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright © 2026 Keith Packard
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following
#    disclaimer in the documentation and/or other materials provided
#    with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
# OF THE POSSIBILITY OF SUCH DAMAGE.
#

srcs_math_two = [
  'pi_32.c',
  'pi_64.c',
  'pi_80.c',
  'pi_128.c',
  'inv_pi_32.c',
  'inv_pi_64.c',
  'inv_pi_80.c',
  'inv_pi_128.c',
  'rem_half_32.c',
  'rem_half_64.c',
  'rem_half_80.c',
  'rem_half_128.c',
  'acospi_32.c',
  'acospi_64.c',
  'acospi_80.c',
  'acospi_128.c',
  'asinpi_32.c',
  'asinpi_64.c',
  'asinpi_80.c',
  'asinpi_128.c',
  'atanpi_32.c',
  'atanpi_64.c',
  'atanpi_80.c',
  'atanpi_128.c',
  'atan2pi_32.c',
  'atan2pi_64.c',
  'atan2pi_80.c',
  'atan2pi_128.c',
  'canonicalize_32.c',
  'canonicalize_64.c',
  'canonicalize_80.c',
  'canonicalize_128.c',
  'cospi_32.c',
  'cospi_64.c',
  'cospi_80.c',
  'cospi_128.c',
  'sinpi_32.c',
  'sinpi_64.c',
  'sinpi_80.c',
  'sinpi_128.c',
  'tanpi_32.c',
  'tanpi_64.c',
  'tanpi_80.c',
  'tanpi_128.c',
  ]

src_libm_math_two = files(srcs_math_two)
