libc_a_SOURCES += \
	%D%/memcmp.S \
	%D%/memcmp-stub.c \
	%D%/memcpy.S \
	%D%/memcpy-stub.c \
	%D%/memset.S \
	%D%/memset-stub.c \
	%D%/setjmp.S \
	%D%/strlen.S \
	%D%/strcat.S \
	%D%/memmove.S\
	%D%/strcmp.S \
	%D%/memchr.S
