#include <_mingw.h>
#include <assert.h>
#include <conio.h>
#include <ctype.h>
#include <dir.h>
#include <direct.h>
#include <dirent.h>
#include <dos.h>
#include <errno.h>
#include <excpt.h>
#include <fcntl.h>
#include <fenv.h>
#include <float.h>
#include <inttypes.h>
#include <io.h>
#include <limits.h>
#include <locale.h>
#include <malloc.h>
#include <math.h>
#include <mbctype.h>
#include <mbstring.h>
#include <mem.h>
#include <memory.h>
#include <process.h>
#include <search.h>
#include <setjmp.h>
#include <share.h>
#include <signal.h>
#include <stdarg.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <tchar.h>
#include <time.h>
#include <unistd.h>
#include <values.h>
#include <wchar.h>
#include <wctype.h>
#include <sys/fcntl.h>
#include <sys/file.h>
#include <sys/locking.h>
#include <sys/param.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/timeb.h>
#include <sys/types.h>
#include <sys/unistd.h>
#include <sys/utime.h>

int main()
{return 0;}
