#!/bin/bash

HERE="$(dirname $0)"

declare -A tools

tools=(['arm']=arm-linux-gnueabihf-gcc)
tools+=(['aarch64']=aarch64-linux-gnu-gcc)
tools+=(['x86']=x86_64-linux-gnu-gcc)

declare -A run

run=(['arm']=qemu-arm)
run+=(['aarch64']=qemu-aarch64)
run+=(['x86']=env)


declare -a arch

arch=(arm aarch64 x86)

declare -a headers


copyright() {
    cat <<\EOF
/*
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Copyright © 2026 Keith Packard
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */
EOF
}

wrap() {
    ARCH=$1
    HEADER=$2
    OUT=$3
    DIR=$(dirname ${OUT})
    mkdir -p $DIR
    CC="${tools[$ARCH]}"
    RUN="${run[$ARCH]}"
    UP=$(echo $HEADER | tr a-z A-Z)
    SOURCE="${HERE}"/make-${HEADER}.c
    EXEC=make-${HEADER}-${ARCH}
    "${CC}" ${SOURCE} -o ${EXEC} || exit 1
    (
    copyright
    
    DEF="_LINUX_${UP}_H_"
    echo "#ifndef ${DEF}"
    echo "#define ${DEF}"
    if [ $HEADER = errno ]; then
	"${RUN}" ./${EXEC} || exit 1
    else
	"${RUN}" ./${EXEC} | sort -nk3 || exit 1
    fi
    rm "${EXEC}"
    echo "#endif /* ${DEF} */") > $OUT
}

headers=(errno fcntl syscall)

for a in "${arch[@]}"; do
    for h in "${headers[@]}"; do
	OUT="machine/$a/linux/linux-$h.h"
	wrap $a $h $OUT || exit 1
    done
done

