LIBM_CHEWOUT_FILES += \
	%D%/cabs.def %D%/cacos.def %D%/cacosh.def %D%/carg.def \
	%D%/casin.def %D%/casinh.def %D%/catan.def %D%/catanh.def \
	%D%/ccos.def %D%/ccosh.def %D%/cexp.def %D%/cimag.def %D%/clog.def \
	%D%/clog10.def %D%/conj.def %D%/cpow.def %D%/cproj.def %D%/creal.def \
	%D%/csin.def %D%/csinh.def %D%/csqrt.def %D%/ctan.def %D%/ctanh.def

LIBM_CHAPTERS += %D%/complex.tex
