/*
Copyright (C) 2002 by Red Hat, Incorporated. All rights reserved.

Permission to use, copy, modify, and distribute this software
is freely granted, provided that this notice is preserved.
 */
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>

#define CHECK(a) { \
  if (!(a)) \
    { \
      int err = errno; \
      printf ("Failed " #a " in <%s> at line %d\n", __FILE__, __LINE__); \
      fflush(stdout); \
      exit(err == ENOMEM ? 77 : 1); \
    } \
}

#ifdef _TINY_ICONV
#define _ICONV_FROM_ENCODING_US_ASCII
#define _ICONV_TO_ENCODING_US_ASCII

#ifdef _MB_CAPABLE
#define _ICONV_FROM_ENCODING_UTF_8
#define _ICONV_TO_ENCODING_UTF_8

#ifdef _MB_EXTENDED_CHARSETS_ISO
#define _ICONV_FROM_ENCODING_ISO_8859_1
#define _ICONV_TO_ENCODING_ISO_8859_1
#define _ICONV_FROM_ENCODING_ISO_8859_2
#define _ICONV_TO_ENCODING_ISO_8859_2
#define _ICONV_FROM_ENCODING_ISO_8859_3
#define _ICONV_TO_ENCODING_ISO_8859_3
#define _ICONV_FROM_ENCODING_ISO_8859_4
#define _ICONV_TO_ENCODING_ISO_8859_4
#define _ICONV_FROM_ENCODING_ISO_8859_5
#define _ICONV_TO_ENCODING_ISO_8859_5
#define _ICONV_FROM_ENCODING_ISO_8859_6
#define _ICONV_TO_ENCODING_ISO_8859_6
#define _ICONV_FROM_ENCODING_ISO_8859_7
#define _ICONV_TO_ENCODING_ISO_8859_7
#define _ICONV_FROM_ENCODING_ISO_8859_8
#define _ICONV_TO_ENCODING_ISO_8859_8
#define _ICONV_FROM_ENCODING_ISO_8859_9
#define _ICONV_TO_ENCODING_ISO_8859_9
#define _ICONV_FROM_ENCODING_ISO_8859_10
#define _ICONV_TO_ENCODING_ISO_8859_10
#define _ICONV_FROM_ENCODING_ISO_8859_11
#define _ICONV_TO_ENCODING_ISO_8859_11
#define _ICONV_FROM_ENCODING_ISO_8859_13
#define _ICONV_TO_ENCODING_ISO_8859_13
#define _ICONV_FROM_ENCODING_ISO_8859_14
#define _ICONV_TO_ENCODING_ISO_8859_14
#define _ICONV_FROM_ENCODING_ISO_8859_15
#define _ICONV_TO_ENCODING_ISO_8859_15
#define _ICONV_FROM_ENCODING_ISO_8859_16
#define _ICONV_TO_ENCODING_ISO_8859_16
#endif

#ifdef _MB_EXTENDED_CHARSETS_JIS
#define _ICONV_FROM_ENCODING_JIS
#define _ICONV_TO_ENCODING_JIS
#define _ICONV_FROM_ENCODING_EUC_JP
#define _ICONV_TO_ENCODING_EUC_JP
#define _ICONV_FROM_ENCODING_SHIFT_JIS
#define _ICONV_TO_ENCODING_SHIFT_JIS
#endif

#ifdef _MB_EXTENDED_CHARSETS_WINDOWS
#define _ICONV_FROM_ENCODING_CP437
#define _ICONV_TO_ENCODING_CP437
#define _ICONV_FROM_ENCODING_CP720
#define _ICONV_TO_ENCODING_CP720
#define _ICONV_FROM_ENCODING_CP737
#define _ICONV_TO_ENCODING_CP737
#define _ICONV_FROM_ENCODING_CP775
#define _ICONV_TO_ENCODING_CP775
#define _ICONV_FROM_ENCODING_CP850
#define _ICONV_TO_ENCODING_CP850
#define _ICONV_FROM_ENCODING_CP852
#define _ICONV_TO_ENCODING_CP852
#define _ICONV_FROM_ENCODING_CP855
#define _ICONV_TO_ENCODING_CP855
#define _ICONV_FROM_ENCODING_CP857
#define _ICONV_TO_ENCODING_CP857
#define _ICONV_FROM_ENCODING_CP858
#define _ICONV_TO_ENCODING_CP858
#define _ICONV_FROM_ENCODING_CP862
#define _ICONV_TO_ENCODING_CP862
#define _ICONV_FROM_ENCODING_CP866
#define _ICONV_TO_ENCODING_CP866
#define _ICONV_FROM_ENCODING_CP874
#define _ICONV_TO_ENCODING_CP874
#define _ICONV_FROM_ENCODING_CP1125
#define _ICONV_TO_ENCODING_CP1125
#define _ICONV_FROM_ENCODING_CP1250
#define _ICONV_TO_ENCODING_CP1250
#define _ICONV_FROM_ENCODING_CP1251
#define _ICONV_TO_ENCODING_CP1251
#define _ICONV_FROM_ENCODING_CP1252
#define _ICONV_TO_ENCODING_CP1252
#define _ICONV_FROM_ENCODING_CP1253
#define _ICONV_TO_ENCODING_CP1253
#define _ICONV_FROM_ENCODING_CP1254
#define _ICONV_TO_ENCODING_CP1254
#define _ICONV_FROM_ENCODING_CP1255
#define _ICONV_TO_ENCODING_CP1255
#define _ICONV_FROM_ENCODING_CP1256
#define _ICONV_TO_ENCODING_CP1256
#define _ICONV_FROM_ENCODING_CP1257
#define _ICONV_TO_ENCODING_CP1257
#define _ICONV_FROM_ENCODING_CP1258
#define _ICONV_TO_ENCODING_CP1258
#define _ICONV_FROM_ENCODING_KOI8_R
#define _ICONV_TO_ENCODING_KOI8_R
#define _ICONV_FROM_ENCODING_KOI8_U
#define _ICONV_TO_ENCODING_KOI8_U
#define _ICONV_FROM_ENCODING_GEORGIAN_PS
#define _ICONV_TO_ENCODING_GEORGIAN_PS
#define _ICONV_FROM_ENCODING_PT154
#define _ICONV_TO_ENCODING_PT154
#define _ICONV_FROM_ENCODING_KOI8_T
#define _ICONV_TO_ENCODING_KOI8_T
#endif

#endif
#endif
