#!/bin/sh
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright © 2019 Keith Packard
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following
#    disclaimer in the documentation and/or other materials provided
#    with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
# OF THE POSSIBILITY OF SUCH DAMAGE.
#
DIR="$(dirname "$0")"

# First argument must be target architecture

case "$1" in
    "")
	echo "Usage: $0 <architecture>" 1>&2
	exit 1
	;;
esac

export ARCH="$1"
shift

# Find cross compile configuration

CROSS="$DIR"/cross-"$ARCH".txt

if [ -f "$CROSS" ]; then
    :
else
    echo "$0: $ARCH not supported" 1>&2
    exit 1
fi

# 'clang-' prefix uses clang instead of gcc

case "$ARCH" in
    clang-*)
	ARCH=$(echo "$ARCH" | sed 's/clang-//')
	;;
esac

case "$*" in
    *-Dio-long-double=true*)
	case "$ARCH" in
	    *rv[36][24]*|*riscv*|*aarch64*|*power9-fp128*|*sparc*)
		case "$*" in
		    *-Dtinystdio=false*)
			echo "io-long-double for legacy stdio not supported on riscv, aarch64, power-fp128 or sparc"
			exit 77
			;;
		esac
		;;
	    *power*|*avr*)
		echo "io-long-double not supported on power double double or avr"
		exit 77
		;;
	esac
	;;
esac

# Check for sysroot-install and automatically set prefix if needed

case "$*" in
    *sysroot-install=true*)
	case "$*" in
	    *-Dprefix*)
		:
		;;
	    *)
		SYSROOT_ORIG="$("${ARCH}-gcc" -print-sysroot)"
		SYSROOT="$(readlink -f "$SYSROOT_ORIG")"
		PREFIX="-Dprefix=$SYSROOT"
		;;
	esac
	;;
esac

# Run meson

case "$PREFIX" in
    "")
	meson setup \
	      -Dincludedir=picolibc/"$ARCH"/include \
	      -Dlibdir=picolibc/"$ARCH"/lib \
	      --cross-file "$CROSS" \
	      "$@" \
	      "$DIR"/..
	;;
    *)
	meson setup \
	      -Dincludedir=picolibc/"$ARCH"/include \
	      -Dlibdir=picolibc/"$ARCH"/lib \
	      --cross-file "$CROSS" \
	      "$PREFIX" "$@" \
	      "$DIR"/..
	;;
esac
