#!/bin/sh
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright © 2020 Keith Packard
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following
#    disclaimer in the documentation and/or other materials provided
#    with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
# OF THE POSSIBILITY OF SUCH DAMAGE.
#

dir="$(dirname "$0")"

# select the program
elf="$1"
shift

done=0
while [ $# -gt 0 -a $done -eq 0 ]; do
  case "$1" in
    --stdin)
      if [ $# -lt 2 ]; then
        echo "Error: --stdin requires a quoted string"
        exit 1
      fi
      stdin="$2"
      shift 2
      ;;
    --args)
      if [ $# -lt 2 ]; then
        echo "Error: --args requires a quoted string"
        exit 1
      fi
      args="$2"
      shift 2
      ;;
    *)
      done=1
      ;;
  esac
done

qemu="qemu-system-m68k"

# Point the semihosting driver at our new chardev

semi=enable=on,chardev=stdio0,arg="program-name $args"

case "$elf" in
    *_softfp)
        elfbase=`echo "$elf" | sed 's/_softfp//'`
        ;;
    *)
        elfbase="$elf"
        ;;
esac

case "$elfbase" in
    *m5307|*m51qe|*m5329|*m5407|*m54455|*m5475)
        CPU=any
        ;;
    *m5206|*m5206e)
        CPU=m5206
        ;;
    *m5208)
        CPU=m5208
        ;;
    *m680?0)
        CPU=`echo "$elfbase" | sed 's/.*\(m680.0\)$/\1/'`
        ;;
    *)
        CPU=m68020
        ;;
esac

echo "$stdin" | $qemu \
  -chardev stdio,id=stdio0,mux=on \
  -machine virt \
  -cpu "$CPU" \
  -semihosting-config "$semi" \
  -monitor none \
  -serial none \
  -net none \
  -nographic \
  -kernel "$elf" "$@"
