#!/bin/sh
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright © 2019 Keith Packard
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following
#    disclaimer in the documentation and/or other materials provided
#    with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
# OF THE POSSIBILITY OF SUCH DAMAGE.
#

dir="$(dirname "$0")"

qemu="qemu-system-ppc64"

# select the program
elf="$1"
shift

base=`basename "$elf" .elf`
one_elf=`mktemp --suffix=.elf "$base".XXX`
one_bin=`mktemp --suffix=.bin "$base".XXX`

trap 'rm -f "$one_elf"' 0 1 15
trap 'rm -f "$one_bin"' 0 1 15

objcopy=powerpc64-linux-gnu-objcopy

$objcopy "$elf" -Obinary $one_bin 2>/dev/null

$objcopy --update-section .init="$one_bin" --remove-section=.text --remove-section=.sfpr --remove-section=.toc --remove-section=.data "$elf" "$one_elf" 2>/dev/null

mon=none

"$dir"/monitor-e9 $qemu \
	-nodefaults \
	-device ipmi-bmc-sim,id=bmc0 \
	-cpu power9 \
	-monitor none \
	-serial none \
	-device isa-serial,chardev=s1 \
	-chardev stdio,id=s1 \
	-machine powernv,accel=tcg \
	-kernel "$one_elf" \
	-nographic "$@" < /dev/null
