name: Docker Image Builder

on:
  schedule:
    # We build 5:00 UTC every day
    - cron: '0 5 * * *'

env:
  IMAGE_FILE: dockerimg.tar
  IMAGE: picolibc

jobs:
  cache-maker:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date -u +'%Y%m%d')"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build picolibc container
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          file: .github/Dockerfile
          tags: ${{ env.IMAGE }}:latest
          outputs: type=docker,dest=${{ env.IMAGE_FILE }}

      - name: Check size
        run: |
          ls -al

      - name: Cache the Docker Image
        uses: actions/cache@v2
        with:
          path: ${{ env.IMAGE_FILE }}
          key: ${{ env.IMAGE_FILE }}-${{ steps.date.outputs.date }}-${{ hashFiles(format('{0}', env.IMAGE_FILE)) }}
