#!/bin/bash

cat head-zephyr

for build in minsize release; do
    for arch in zephyr; do
	echo "  $build-$arch:"
	cat variants
        cat <<EOF
        test: [
          "./.github/do-zephyr",
        ]
EOF
	cat steps-head
	cat steps-$build
    done
done
