#!/bin/bash

cat head-coreboot

for build in minsize release; do
    for arch in coreboot; do
	echo "  $build-$arch:"
	cat variants
        cat <<EOF
        test: [
          "./.github/do-coreboot",
        ]
EOF
	cat steps-head
	cat steps-$build
    done
done
