name: Minsize RISC-V

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_FILE: dockerimg.tar
  IMAGE: picolibc
  HASH_FILE: picolibc/.github/packages.txt

jobs:
  cache-maker:
    runs-on: ubuntu-latest
    steps:
      - name: Clone picolibc
        uses: actions/checkout@v2
        with:
          path: picolibc

      - name: Cache the Docker Image
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.IMAGE_FILE }}
          key: ${{ env.IMAGE_FILE }}-${{ hashFiles( env.HASH_FILE ) }}

      - name: Set up Docker Buildx
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/setup-buildx-action@v1

      - name: Build picolibc container
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          file: .github/Dockerfile
          tags: ${{ env.IMAGE }}:latest
          outputs: type=docker,dest=${{ env.IMAGE_FILE }}

  test:
    needs: cache-maker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        meson_flags: [
          "",

          # Math configurations
          "-Dnewlib-obsolete-math=false",
          "-Dnewlib-obsolete-math=false -Dwant-math-errno=true",
          "-Dnewlib-obsolete-math-float=true -Dnewlib-obsolete-math-double=true",
          "-Dnewlib-obsolete-math=true",
          "-Dnewlib-obsolete-math=true -Dwant-math-errno=true",

          # Tinystdio configurations
          "-Dio-float-exact=false",
          "-Dio-long-long=true",
          "-Dformat-default=integer",
          "-Dformat-default=float",

          # Malloc configurations
          "-Dnewlib-nano-malloc=false",

          # Original stdio configurations
          "-Dtinystdio=false -Dnewlib-io-float=false",
          "-Dtinystdio=false -Dnewlib-io-float=false -Dio-long-long=true",
          "-Dtinystdio=false -Dnewlib-io-float=true",
          "-Dtinystdio=false -Dnewlib-io-float=true -Dio-long-long=true",
          "-Dtinystdio=false -Dnewlib-io-float=true -Dio-long-long=true -Dnewlib-io-long-double=true",

          # Locale configurations
          "-Dnewlib-locale-info=true -Dnewlib-locale-info-extended=true -Dnewlib-mb=true",

          # Iconv configurations
          "-Dnewlib-iconv-external-ccs=true",

          # Multithread disabled
          "-Dnewlib-multithread=false -Dnewlib-retargetable-locking=false",
          "-Dnewlib-multithread=false -Dnewlib-retargetable-locking=false -Dtinystdio=false",
        ]
        test: [
          "./.github/do-test do-riscv-configure build-riscv",
          "./.github/do-test do-rv32imac-configure build-rv32imac",
          "./.github/do-build do-clang-riscv-configure build-riscv-clang",
          "./.github/do-test do-clang-rv32imafdc-configure build-clang-rv32imafdc",
        ]

    steps:
      - name: Clone picolibc
        uses: actions/checkout@v2
        with:
          path: picolibc

      - name: Restore the Docker Image
        uses: actions/cache@v2
        with:
          path: ${{ env.IMAGE_FILE }}
          key: ${{ env.IMAGE_FILE }}-${{ hashFiles( env.HASH_FILE ) }}

      - name: Check
        run: |
          ls -al

      - name: Load and Check the Docker Image
        run: |
          docker load -i $IMAGE_FILE
          docker images -a $IMAGE

      - name: Minsize test
        run: |
          docker run -v $(readlink -f picolibc):/picolibc -w /picolibc $IMAGE ${{ matrix.test }} ${{ matrix.meson_flags }} --buildtype minsize

      - name: Check Disk Space
        if: always()
        run: |
          df -h
          docker buildx du --verbose
