LIBC_CHEWOUT_FILES += \
	%D%/fdopen64.def \
	%D%/fgetpos64.def \
	%D%/fopen64.def \
	%D%/freopen64.def \
	%D%/fseeko64.def \
	%D%/fsetpos64.def \
	%D%/ftello64.def \
	%D%/tmpfile64.def

LIBC_CHAPTERS += %D%/stdio64.tex
